# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:R3RwG3Qf/SoAfYhzpQ==,iv:KcXYhyzKNJUhXwIY1DzNpidoEekrCRjHIOA7aPp+wjg=,tag:gpM774YR5Cj116B4xl72bA==,type:str]
    DOMAIN_1: ENC[AES256_GCM,data:YDAtC2avqxDFLN7Ccg==,iv:m5QzpInDBilBbUPZlA+jXnWdZ7kRxObg2fSkpUaHENw=,tag:f9FU8gqYfB/NeEL5TID/Og==,type:str]
    DOMAIN_2: ENC[AES256_GCM,data:oMuOYItm5w==,iv:4IvihCYmGbyjy80O0hWh1rEQ4o1dJTs4bTy2jrl76d4=,tag:y/8IUongLNymAxboBSB8nQ==,type:str]
    DOMAIN_3: ENC[AES256_GCM,data:XUyOxm5n+sr95Q==,iv:fMwAmPqvfGs+/lpvM7PNvTtpXw1oAYzr/mhDgUgRkIM=,tag:iBo3Son9E1lWstF7sWGN7w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fnM4pHmHib6NEeVxFA==,iv:kM1Kv8SYwIvt4UFNwmACCh6woJMuYF02XOred2YZVSA=,tag:r+68LVk/5MH2m5w9MrfAdQ==,type:str]
    MINIO_ADDR: ENC[AES256_GCM,data:Cm+3Zlk+BTrEX7w=,iv:/shE87LCF5qCl2pseMU+MFiHfny+h6V6utwW/VY3oR8=,tag:n2ATaoMl10193U6iJMRoqg==,type:str]
    NAS_ADDRESS: ENC[AES256_GCM,data:4UQmB5i2HAuIbwg=,iv:2gLk75IqmszGFMq0IVBR7PShns64pMCvO/wXoGZ02zE=,tag:1VLeEmgLYGQENTVjePbN3g==,type:str]
    POSTGRESQL_ADDRESS: ENC[AES256_GCM,data:Al4gMnz42j90xdM=,iv:/H/7kva1R6e97vlfiKsQ5TIY4nNqtI/7kDqESCughRA=,tag:bx7dcya2d+rlbeaPfmRanw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-29T03:15:58Z"
    mac: ENC[AES256_GCM,data:CKThX+0groR/JYQ0FLZGV77snuQ8jBwjGKB1f3ZwjphzWoYdjloDJMxKSgMglGPVoSpRWE8FfNLY79jajiEeBYNAMtI9jLDbkPumvwmZ+Z+1cDdfjF2uMCXLRHPCCpNg3bc1d9jJHTZMjQxR5XKQCMUDs05qq7k+mY3SJ6jvSFk=,iv:sgs3g0NodFSjF4nKyGWFGEeZM1566bdB4XsF4Y/pcnc=,tag:wGQSKs5Yc3VB11ySMAXqfg==,type:str]
    pgp:
        - created_at: "2022-10-31T03:56:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAApZWSd8jJJzoT/JemudIB16tmpoZ3CD+J0GdFUG9bQlt1
            lWL5MvJbju1ilRKkKQxXZwFocOxm0WWK7ilF530Xk77PyH+M+tpCTuA2XAXcf4gF
            m0xUai3KSc8suXdoQMkCEorVKx2yWJG5xqz8vxW8QJnCzRShpZzyERWoTKNe5SZD
            Wr+dDFa+Wh5+Rpa1+T5MKEOPCflJoV6SpviZJt2N8kjfeILbmGfxQcFuUIZY5Odi
            /l8JvMQy/Pt4dMNBhneFGpia5zdDMegh3+08kyjTRK3chOwrNi4ESaV96JWrjarj
            56yrTnviMm5jcpWPD6iE2lvyv4Cn2F01Hx5VFhRZo/A4AyXRgfjGNASVgmBZlr1V
            ERR6WcWFgGenOIsIpD0ukNrR6vVCfvRUtqfOzh0fjvGV/oecbfunnHlbwDxWPCSR
            gGXsIX70VwZFQjyazgklOtNn3ENpcW9p8T8fF8UAKGVAa6a4HE59e3pQcKT9KgtV
            a/mp5xvbyWic6ygAxg4/OPRu300CbE5smDPyDg+wMqA0edW2L3oSmmTNZFd5RXFf
            qurpDeTLXaKCCv+4MprHBDgVyx5ttaTLNR0Q8XRBcwm9ibf7rpGXLVAUAYN4sDIo
            O5AdN4bX7Ypx7ETupC+GwZ37mrEj9En19NGRKOl+MIPpDr7m3RSqBR/1FcjLQkXU
            ZgEJAhDH2xiax0ytl1spUfQwRFTiLUyM/XalMoVgSfhvm3PwXfSFL6FCxEse8gxq
            PRWPeQzSJOFpOwCOD7fuQ3ehgsy/ddkW8AcNX1Yz13gfdUn6Z/fNQ08o0hJUCyik
            nf3ntNf8Pg==
            =h1hj
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2022-10-31T03:56:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAsujw+kf0q/rOD/unk2ujiKb6ZJ3HTFpuMFDzgDNcpJXO
            OGEzBZGzhZt/6aYmUk1J3hozC+O8HQ06kp1Xh3//rxFIo6ywlKMP8B8+XKSeeYvB
            DIxoJnlaED8nKlb/6Kt7SQapYjYqz3HbFv/nCO3plbTFQ0oI0zn6wct1YkS7pPBw
            AUPCdZuVzCXgIrpaojYUl+Tamv9UXk7sg4uRwohfzZiKNiVeDKbmDF5WylQCLx3e
            /dAP2EwZeU8bjGR8gCHo7VWojb+UhxnuxeuJJpFaHi1Ha+tXl4M+pwQQPr7ZP8Ua
            BaiZoV11fooIEPoNEUJrl9t0t5H965kYplF5hR67DvMWoCd1k2XF4Cm5UjApo1Ak
            L8evZbE3JA+Wz50bGYUA9lQFhj3eHmrlgZo3sQZ+ska2selzKoRrfm2Bby5nt76m
            7Eg7i4FTda9alEQ54COQz9bdoNx0dj6Pc4zy5TlvBpb6fiwOpYqDlME+ZROtbEHd
            Pe99NXHFfqTUFMLyJU5Ye0Ki1KRDG3I+RRCA9jd8QUdp2xeo9CqGj/A/LbS8u3/i
            Hp3aTpXr4kxud6gbYwDLPYogCoQtgpHyz4gQKPkYKHiveEAPpFL5iPMW7E7FYCNe
            FOr+qu3aZIR6xsvl/69zmkv5hr4AyhGJEWeKwhvIfuRPxl7hZ9Ixhps3g7x5pmvS
            UQHAUzomMNlpRC4WdRBhNZusEiZtl0RY7IVzX0bL1Np0qtR6XOkTlXVszM1eYYqK
            4zyFVYVyNgVN1xsTFQ5WGTZSnO7q51PR1MT1vjgTOyHoig==
            =L8Vq
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
