---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/clusters/cluster-1-cloud-oci/deployments/apps/hashivault/vault/app"
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster