---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/clusters/cluster-1-cloud-oci/deployments/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: secrets
  decryption:
    provider: sops
    secretRef:
      name: sops
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: global-settings
      - kind: Secret
        name: global-secrets
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: global-settings
              - kind: Secret
                name: global-secrets
              - kind: ConfigMap
                name: cluster-settings
              - kind: Secret
                name: cluster-secrets
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
