---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - secret.sops.yaml
configMapGenerator:
  - name: cloudflare-tunnel
    files:
      - config.yaml=config.yaml
generatorOptions:
  disableNameSuffixHash: true