# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_PUBLIC_IP: ENC[AES256_GCM,data:noNjxTUEymiL9eTFiLA=,iv:/g4gdWE8h0plZg8qb4aUZjE1Z/+rCWmh7HxUQs8KsEQ=,tag:uzb6eNX3j80MGOISyszVgA==,type:str]
    LB_ISTIO_INGRESS_GATEWAY: ENC[AES256_GCM,data:6LLSg1PyIYRtjclAJmQ=,iv:9Ij5j71xQ0fpKClYLJj+UJTJAUEvm00jp1ex5PFs2ok=,tag:HNqgSl5htaYWTOy0P0onwA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4BnUpfzzLPjbwghBq5zSF7kU070T+PX2PJJ6FeYWrnt/PYM9,iv:W4N4VCSmC3+4EKdJPjXehzu0IMUDwaOa/+79V7hWiT0=,tag:0f2a2qidXEeM56JaOuGYSA==,type:str]
    POSTGRES_SSO_ADMIN_PASSWORD: ENC[AES256_GCM,data:Pp18mzSRpzH5COi4GP4moc1I2JtsoTVLCBle8lFo3V3L,iv:/wHWGlC3FtGgwN8Y6Zqn/jNhbO4m1sAoKw/VKgNjG9c=,tag:0qPxB9Tu3dbX3dQW4D9DjA==,type:str]
    POSTGRES_SSO_USERNAME: ENC[AES256_GCM,data:yCf7H7qEVrQ=,iv:52U29CagR19t/S8bmFMSRRzBsxR7TPo5P2OvjGIGgPk=,tag:z60l9yqPRCBvsuwMQc4vPw==,type:str]
    POSTGRES_SSO_PASSWORD: ENC[AES256_GCM,data:bQuil1M8ze/aALlftGKpBFbNgbI68vUtbVkWdzk/S1ZbuBXp2mY=,iv:Zl71lIQaAuz98z13TzDuND6x44xX2DYry3u/vVx8m3U=,tag:iPegtTFcJ/5zwAZvHnmZ5g==,type:str]
    KEYCLOAK_ADMIN_USER: ENC[AES256_GCM,data:ILdvlfPsDQ==,iv:LlzKpclfGuOEKrHcxGuGc/YTCR23yTy7JFOc+9RH82A=,tag:n+w5D8GJm1FQWV7aYgdYfA==,type:str]
    KEYCLOAK_ADMIN_PASS: ENC[AES256_GCM,data:nA4dC3HS6b3rKdZoeeEaLxrmnbSzHGXfekFo4xTF,iv:GQrP94yeGqwoERQX3hsoB6xfCKJ4etxwL6TVeuqxIIQ=,tag:JMx9jTIsYmmnbq0Hpe6Sew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-17T02:04:19Z"
    mac: ENC[AES256_GCM,data:xlOjDvr4y1OmLkII1ctPX+9vWL55UIXZQBvNRUcNoaViznS1W/72Dxq2lXKEm3aySwGAnDRGGZ9L0au00W1E652Cr9Q8aOZ8XNJteX75zHzFgxxd2VKMNYjn908SNfUZG0/kN+ks28V3310+o8vGLhDtleoL/M4Nd3DLYokkheM=,iv:Nyx+okPxarJTo5FasqfID/WPUOG5dD0d+FVbcxXZkPs=,tag:qdDUljhvUZUMAcXwjGbAxw==,type:str]
    pgp:
        - created_at: "2023-05-17T02:04:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAArkkWtDj+l5kDh3A9BknmjMeMRvukF7f21jYvwhoVAmIN
            K+uJq/41cM7QwYTJDr7O23WERJJrKjZmO/NtU9ogzqPHWu/MiAPr/zGXovsgPemv
            WrcG2amN6BsYb0Q4ucOvpwRKwY7OMfH6a3ih+ISodFWTlz93NVBxrybI4fhQ5DNm
            oXFcSEfhUjFBaYUIpTz9/EngciVyhJdpFlSCmgYNziYFQLrKidhX4JEx6bwlufph
            bdA148XEMyloqunPCqFhOR1Huw/9eT83NHvy8g/iymifPoThTLEPulsARakswBE+
            JTt/omoCG5G3NFSi59j0fXTZgXcntoqzaHgfWyxROdW2nBxfaq26sX+Pb4a4hdC2
            sjcX1YD7rt58Iy7YvULbLieksfUQgPHOtBXyXH3gZA8YdEXlQoEbMJX3hx1ULz7d
            DIcFFu6ZpzBpKUs+vkrql/m431+EPX+OaLiOZL22KEJOlFa7vYlRp0vaE/DaXVLh
            yVFDZ7x+k7QbMRWHBqJE4PNgPDq7v/zZLxEOBXlHVYQgjXCVoyJkIlFll0o/VDPN
            jYNXEWzmE86ZhEEdDfKfijChAFDijiL0UbPOzis6pAwXeBrBJqXHhvcsrSfDRESB
            O32Z9dd6z7IRXuy7Y3WnwhqP8Qzfj53JeS/Mf5dbjpgFwcR2FJ3vyWVmr9AfWp7U
            ZgEJAhA/AQn6Mb+GxCrk+U+ZVFeR0y883IW7NwK0jHqQxN0pOcPmshKUe/jK1OHK
            AXUFTkIJG0oJGQWCGXbY97KLagxYjfyFrAIq4uoU+qraymrRGJasF18fN9F12cOs
            a9DgM6Ik7g==
            =bVP3
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2023-05-17T02:04:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCARAAjzVqe+gFS7mrKj735e5p4tX5/LivuzIaA7TJ86koYgob
            OxNBUiMeb04xvBnnUpdrBqOv3TZOYmkYXT9xoi2fQgHBaHvdXtswUn0+eL/aoEmA
            7pEJMTM7Ig4ySVudyM5wq3uecCjb8REMn+q5kN3r9kCc7LkKKYDhIr6inrFvNv3r
            FNivbmhQrgTEdtTJxAItW5qVd9NONjjwUIzqpNv4u3vgOu5sTd5/Ho4CKbFW97YH
            KzOu2eIv5D11md9A9IQUdeVzKfrgarjMmBz+q5zw9PigmnmQPEmipy4uUdGhOibq
            SYMCuR+AgW5HNIhXBHurTFMjP38RcjcR7mOT18yjEdjAzIpAxGibaPmv4X9ov8Hh
            lf+d7OkR8xZB3s3OdBooRhuu/1g/Vbbb6ZKSVUEHFiPFj+5RYGa7AGonkNcDE8Q+
            wFCglf7CcVa4Cc8zLKeGnx+Taoh7PAQyDW0/5jihxHyNaI+fwfet2CECpts8Db+u
            mCrdvxeYc9nDlPyzeO0mAD5o24jRi9sGeGqATpOgie1sTjhpRWRYdgH0MEHVxVSV
            6+hc6nNIcfeDsfpBPd1xg7XvQ6lM3mHYcLVsLpbd7hUUeKli4/MDGIWtzCwzBif3
            zl6HPKD0QcpQ56yJhwXzV4877a49mQqzXIN4yp5e/fZLINMxyXzYmapnuLSQNGPS
            XAEow6FVEu8tl72REdR45kcXchllOWU20Za5m+Fo8NopGix2ZeFHD+du/pvlqXSw
            HkiLK7EjtH57bYG783ILkL9/VHAc4RShXRXaj76N4ITpCKADaQQ2XfdL9DJt
            =N9PQ
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2023-05-17T02:04:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++AQ//cH2kruqAZQewZgbGXM6n1nFdyMI4dF2M8DAXYiXE8XV+
            raQYtSzg1DPbOCMxtlazpVza7VpDWm1yPlW/vFGoaMpZ1azDvjPPlr0wFw21+IwQ
            SulC8KZkB1tTpvDJwRve+Ew6z0QslM87s97j+HR7Li56UdFfHCcHdxw2g5w5rfAP
            kcmUX/1XpLypqe1GmB7Qbb52Z+wfNgAZeP+wva6MNsVBzswbZND7zBUrUf/WtG/x
            p+i9LNwtepn5GQh2dk6FVoCnqUYFuiYN7Lftin2tpodK9BkOMR4l7trI80xEuHdk
            +/fpEmGQlw3n1vuAMRHCspVNh94oqvsTu+vKlnwfS0pF4IOdwz1ofqLctT9DoDAM
            QvnKdHRet4QbvjFMhi00t3VWKAV4/R2oVSD2KpQvXyqsi3tI0ggz25yRgGEYYlCG
            hxWsetDHHWi7qNW5r/TjC/ik4JUdEFYz1iyjko5klvnnefAufO33izctvMxfyen9
            rNYGV3N0EIDdnJ0xwnGx5BMWFmSwu9DHQTkFhqD6cbIEgIzqz0M7yGIjb1UfIsI3
            D17yYxngTVesc2cPUBC1PeGfaVS2ObIxwT+8yjqI9BSoMAnBDn/tg4qnCE8EBFk9
            1TFFxsevG2z3GYQMN3x3hrDwI0MCPBS5e2UHcLdi4IaiZjBfSuwfeS8gvwTxOV/S
            XAF8J8YTKl7tR9FxaSPU8Y47Qn2M9rkRtBXMjJHa1Sbmf/i9Rl+Ei4D2V2vnWadN
            avKjD5wCE2byhBIPJozY+g4nMt6sbUAw6hyr4/P/UjesGUnf4JAcqqwD1zgz
            =nZwd
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
