# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_PUBLIC_IP: ENC[AES256_GCM,data:MfdngAxd3+jd2medlwg=,iv:IpMgJwG7O46n03jQ3Nk956YO+8r7Na3YEVzXRe6lgqs=,tag:RKnaJhZQgcoAE1uhtHyiKg==,type:str]
    LB_ISTIO_INGRESS_GATEWAY: ENC[AES256_GCM,data:jc4+3iYIGH36J25U/S4=,iv:yk8GA8FK+mOhzH1KBOI4BHDp7+Ac3s886Tszi2cuFdU=,tag:V4qQORAVeasJjYYuodv1/A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/uN7wNkEVBuyGKRJpjjKMTCAde8YGm/MVsLwXAaKaoEu1sWd,iv:9UFY1AS487awOnH/wHoqvBPSXg46ZystGNHSj2j2oxY=,tag:vcPmnjuZ4t5dLgZwaLK5Sg==,type:str]
    POSTGRES_SSO_ADMIN_PASSWORD: ENC[AES256_GCM,data:IiWlvNEQ7Ne1x+fHwXYsc01Du+iSflCNMmcToU9kQ/BG,iv:fA0AJzoTs5epZbftpM1ou+jsIbtNdIWY4RQ/0Q5FIOw=,tag:B5/5BSPlvXGqVVa46pRoWA==,type:str]
    POSTGRES_SSO_USERNAME: ENC[AES256_GCM,data:RTGlGHZTzIs=,iv:LZEw8MUqTMrl7wSF5oBPCKXDs2e1FbVswm9v4ezAaWQ=,tag:rPDR6nBQ6oco3v0Jo5xBbA==,type:str]
    POSTGRES_SSO_PASSWORD: ENC[AES256_GCM,data:kyo+JKUSDm51EMzPcIPD/bR6gOTOS18qnYDVKfLDGAGqAa93ne4=,iv:lgy6vMn43Ktd/f2VJcVeXxGTmneTf90pxgXlbWlQrH4=,tag:16voPg5pC8M7NooEP2312g==,type:str]
    KEYCLOAK_ADMIN_USER: ENC[AES256_GCM,data:uLSKEpwBbA==,iv:ZmJ3Mmu9rYjZlT0+aKknfrQAv2kuQ6Ht6lRKohCyKVY=,tag:trNhdPhj2fdUuFDvpNUs2Q==,type:str]
    KEYCLOAK_ADMIN_PASS: ENC[AES256_GCM,data:431n3jArZbr8V3PBW01HPqu+43vUXYyWuCvUE5jR,iv:7em0gSoGFZLwAxgtM+159RUcgCn6Kp9uscfyujw2D9E=,tag:LB0L5uJ7ox0wvzIwfEJlTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-05-22T02:33:39Z"
          enc: vault:v1:vjkHZmLE5uDdrTHM52vwx/BbKoaIYHa2Xq8NF8E2XOpLZA3ZtXxyfzEz13xvUkaH46ydUgSaEI+hBylO
    age:
        - recipient: age19mqhjpr2yqrwz9n3p7cs52tt3090wjt9kskylgquu3839ce6wuksy5ssqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRXFjdStpODhxZ04rYkZZ
            M01qUldnZTNmN0NIa3A1a09Uc1lPTk1ZeERvClFMdVVDQXBHY2QvZlFWUXdRNE1k
            bWFqS205ckI5Y2JnNlN6Z05jVTFwUVUKLS0tIGNuY1N1UmdBNFJrcEN6NXJsZGUx
            VUppK3lVWnBYR0NOamhGRDN3RU1KdFUKa1ICKppde1BDHm561tXbOI563P5vs3AT
            OASLmisiNTbn74CfLQAQkULmzZU4w5nmz8Mbb8brEzzp+wDTp6bUIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-22T02:33:40Z"
    mac: ENC[AES256_GCM,data:D6mlUvnjYEOTop8SqMSquEjGGsZEMvRZW4TK6F5VFu1+SCjyMJyMNWQV9L68PesISwte0dFh9jgPHxE+6RFzRhu46/pwUc7n8l2hqhkrAzKQmSPtOhKl2+0/2/nj/7LWjXGUjjchhxWfT2x9xDDM5BvwQQbWwTjMGeeBaSt3yQ0=,iv:/OQsErj/vuHG9Ry/Dg5KvJij5QbkBDQ+XJtPx2tkCK0=,tag:scubEu/qQmqAq+NOK3GkHg==,type:str]
    pgp:
        - created_at: "2023-05-22T02:33:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQAQ/+JzBV0aeqlkFisqNUenCRQiYy2IBsr5PCslFm02cfaVKo
            cLiIvEC133GKOkvlih9gfIKpYKKnhFY2+dbQCSY0Ci+C9OwnNli8+6ONdtVQ9Y5b
            31JHqHRaSEn9WtZDcsAh4xArIc/fgZK+KdRsnYMbxPROfVrq9ctSiUroTApNA2gW
            Vp++fsqAR95bYycV5w5iivMqKVxogjf9+e6e/cCoDq/uW8O7hhQ+7bjG1JYVPuLi
            aD+sZdHG5E0V9FiIbYRnN2FFD121EyQfPoEuIX12H+kEPi2iLPoXsQTjFUxpFZpE
            0JQIi1AggkoEkmit/h86wbbX3sREt1gKgwk6OM8oyNthtCLppt35DEXQdQPAiAEw
            Q5j2asYexwlsVU9pm0H/cVwPQyPlp1YrjZOyi7p5rrCwiJ21i88ADGGkpjayXIhX
            zafhPZ9oc2eX+CQ20l5tQyNws6QChPdSc0t32Z0tjY+H9Jv5r8TurwQ0MSXZQ05f
            9YzOc8aPYSqk55VFvzfEipGZ5LInAd+Wwl6PXv/SDtadP/ADWMxizJJIOqHPKt0e
            p1SZlJAgmIPd3Qf2xXE+g0JU7pgDYl1GhefESj+5ynS/9qqviIAnNVYGrMDrgIF0
            t1QkckTDxxE4DSD2jWtJ2neQk1f4D0TMLgaNBh4F/ZzTr6DP3Gf4YXNIYyi/QUPU
            aAEJAhDZH6wehl7+qXcGKF2Rbkay/tzRLaXqzad35dLEUiCx3vC4uNNNFLH8bFnR
            xCt+RYxeuHEIE4VHIlkbDqd7f65xh13l+OCtYv1zw4CabYS2dZfWOB3BlrKS2p8S
            ARhk2/u5excg
            =oXbo
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2023-05-22T02:33:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ//Z0GgMxel1DxJQWIPoReNLu2GOcel5YISRb3/GIcqtQsE
            18EOqfwto4/cyNgDUjgaJx3KbnywMJ5uPuD2tcZZj5SLMqHjBKHQXIjBiwKCI1eO
            1UMI1CHh6jd+fYKg5iAJVcXVQGH3BXm/BWKU92Q1hT5GCxx2LoM1gfAl34sAiB9j
            CmhUVy9Ebyd73UX+CRWTZUiOwaiIJSY45nKiZe2II/1DAI0/M9zkuY2Uqi1pw2W2
            wIbVAaKd1hrHzkypzh4uknam5shYWEfa2ShdR3cAJYZX6xcQQNJYhPbI4nQwEjPA
            JtV5dbMcX4doTbrX2C3/4TYJiD2XN9BJxw+MDhLtWkSPqTKmVCdiR0YOlwnc92hO
            EWEw4T8wDxZGsrA9Szi5KX8chPSrJBf7alezPmuCDt6JKwjp8OZ1KWxFJAHIAjmI
            kYTt05q3211l5spCYsheNlz2Egnrjjk4zk1knDKErY+Ghex7JWs/FavKQZgvejZY
            YNmnfhqy/1wZ+oTB3KRpmDsUW+20myvBfKRlmr4NPHzZ7bwkLNBZ/rf8jFxmJS8i
            CH2SftxuzPm5RlHqgtfUpsvYC72rOpThpVpjI59o34P/zcTgu+69oPPFxaO42sjx
            VSo4R/iuVlC5yqeYYwOkUuJTK0d+FNisxALF/PRvHmPOj5NIEypSZQqy5sBfTH7S
            XgEZeEtJloO7PB4qlOMX9XBVUFzyc1s7jJDih08f+NtFg8OOasonYKnQgnl/OsUO
            GvlQDAGKepnpNrwmvNjVi5zSbd+4cIP/LpJoPwWzSzJ2+eJ55sUNj2L1ZGJU/so=
            =W8ur
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2023-05-22T02:33:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++AQ/8CUdufzzG3ti34dYo2RpbQpMQgAUB0siGSsVhYhhYr+JI
            Jj3F1vCfMDyBoB7u3q4nqEDVnm+/NcZYfL1+kqdxb837EI/+w/jbzUqF8Xub19IG
            uMryClgrF+LQ5LL04i8hqGH+NCewow/IgDp4/vBxe5hbWrOGVvaKL32YjRPwqaRN
            DUxu3ShATjeZ/vYc+j+wPx8Cbw/cVK8iqKaJWLbfKVJF0kevuJApUc7upcf2SYZF
            Y6KUOoVMiRosKJ4n1CJMe+jgLHRmeYyKKGGmGyBijWsRK603opqttBFn9pbP+HNe
            YGeYBKpgbdebbF1E6hF9iKiVFDH5jkvLmg5y2c1EtwQ3emrHVaaAwXPwcL8bEP/M
            hPf6nCVMY1aZQDaY4xzQ7DfRuXChnbCr5hBhreBos63shkd0OwyHxwdbYGCr149+
            apwSR9kddKGMn/RkAYQMmVQx8lzgmOC+1P9vVeG93GI44pQFCSKbU+BB4U+UQMCf
            /cqUp9rYnW19REDyjKFc0X6LUJ23N+jBF2ryt/pHwCLeTfM6nAD/p59CPSLqUU29
            joyGlaYzYCv9w0WN/4QckopxFsVZQYEPFlaAkDBRWpkVZht66V/ulAq37Y2+tUZR
            2Ku4nQjD4uygXrkyoHd4Sqd77cg9KLxUdb4jZYntJkdXGXNVUpDTXFwwp4z37ajS
            XgFWvm9Jx6veft/r51TvJ/t36rkLkEKj76kPZEzg1fpV+7+oBhkYIEGWA7Oe0IMe
            fc4HAX4MLFKcPW05sJpqxcCchzWbR6BBYTX/yCcQjB93erMhZKK7QVvyf3v2GGs=
            =2ycn
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
