---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "rmcd-win"
  namespace: istio-ingress
spec:
  secretName: "istio-public-cert-tls"
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  # cert-manager regenerates a new private key on each issuance
  # https://cert-manager.io/docs/usage/certificate/#rotation-private-key
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "rmcd.win"
  dnsNames:
    - "rmcd.win"
    - "*.rmcd.win"
