---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/istio/observability/kiali/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: istiod
      namespace: flux-system