---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../apps/hashivault/vault/app/helm-release.yaml
  - ./secret.sops.yaml

patchesStrategicMerge:
  - ./helm-release.patch.yaml