apiVersion: v1
kind: Secret
metadata:
    name: vault
    namespace: hashivault
stringData:
    VAULT_OCIKMS_SEAL_KEY_ID: ENC[AES256_GCM,data:PBtfIoDQhEryr1vdUpzYi+xfq2qkuWUvHdGDXpqfBhDNi7SfZOiTEMbHPpb9qJiEcztGi37rkkyoL5cOL6MKTuJjk+ePia310WO7Pk6lJf4vEvQF6JnEwBOXo4k=,iv:i5KF8NXhX/a3nt1bNWw15B44jv/GVafp0QC66A7Nfuc=,tag:RuJeyrmGtng2Y4ps9jLM2g==,type:str]
    VAULT_OCIKMS_CRYPTO_ENDPOINT: ENC[AES256_GCM,data:4PRrNZrnctESPu54so4K5wBIETDRsM7JMylVXSbjmb8CISqZSM2Ae1up5xpWFYmOp0NbodhRYTRqomBrBA==,iv:nRmfMy5dS3Gp24+enMuL/Qu3aDHEOzNnizBv60p2RHg=,tag:9Gx+9IvAmyhQAs6R3tOhPg==,type:str]
    VAULT_OCIKMS_MANAGEMENT_ENDPOINT: ENC[AES256_GCM,data:TCgX6ojWZS9n+CpO1lwysD+7OlkxNKQE9cyAbdIs9RjikmAiUmBSUAyT3Ne6tba+pRnaYWJiJ62ByO0F37T4uu8=,iv:3joWjga5mkEdS6w+s01dVY57leNy6a2jhzdKhDrQh9g=,tag:l9jdvPaXkpViI28ge/z9UQ==,type:str]
    VAULT_TOKEN: ENC[AES256_GCM,data:s3j9hbyXZooxfW90OJ0STvrJ,iv:bajNnTgExc1V9utV2l2TePra+PAd1iB7anBzmMGl/rM=,tag:xf4/oL/H5ShmWz0UeKH37A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-17T03:00:47Z"
    mac: ENC[AES256_GCM,data:pa1C1s372tBYCgKvXxyN/4SggFUDx+mMZ2Cn+0chNo0uzjs11BrmHXqvIC7kpuSYcTdXMLWlfSRSqLwSAhIlegqAe8msT2FReHBfmCE2Pdb9q0IFk/o6Uvi+X/jl5O3BvCx+Hg4KgnEvLNvtqWkGSQWgOJXzwzJOAVI7YStMpCw=,iv:gIXdoTv/O7lz+9sbNeQzECzsAbRin62bosaGJk549so=,tag:qPuA2Fs8mZDH5VMYK7/PzA==,type:str]
    pgp:
        - created_at: "2023-04-17T03:00:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILAxnLN2eNn/kQAQ/4sJsosnf2IQ1voE6Oa3uSdOJ/8fwCCn7mgMMbGe4vweXR
            JZp40kr7K7QaUugd9E5N2vbWOXTKhxfz/ARtRip8GLUhEQ0eqTQRpO2+94a/8tsc
            xV/oVN1kiMDDR/x7L6eMOJbz7UCLpGbRZGUFuhp/TKyz09DXG1Ob04ic4WwDsL8J
            T9gPmn3RbdN0pymx7Q8AalrfY7EAfNEt9fhlcDOQadJDMHDdTVlmJnkE1BC/IhUe
            WtY7WmeDVMdx/7TdWb1cWMvLDaTV//dPgf44USU5+mcKjA0ZHp3IZV96rasUeQex
            /k/ZKfQxpUjVtGo3jbf54IW0twLtKXlVECg5csINCjHSNFM4V/1xPR1anug3cpHc
            dFuROHd0wqnlcBWxHEeIZggt8NSfHJlEOJ0/2498D/5KB7NBUDkiaVXExTmNSvhr
            gR55ANCKy6Q1sl8fHzrvYoG/zKjWwsJnISr4PGlZe/ivlnC3qEn28g558L+GknLH
            uXAR1Dwj2DmDqSTUZanJida4XCcFEjLkUJ27oMIspG+ku6WnUfdvfNcM+FPWSWdA
            tKIyQMvxFrwxuMZdQ7t1ySkOaOKs6VYGjiJNncCiX6xvB3nFQNci+7KuA3K9hXU1
            lmM8UMD98rTLziX9mia/CDPS85oSXA5A0aWDZWaItLjT7rVbGwHCXRbJDvH9ddRm
            AQkCEI3On7SbvuFs86fDH8Brdp8blr5DKx7sR6ctmBLjuN8ioJsJ3WY1nCmefiiD
            q+FLay2QGacYTrEX1IVJ2ztvTrRiCuwe1Y29X/pTD9DPsqBJnsnAKmup8afJqCRe
            cbeDvl0A
            =I6j/
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2023-04-17T03:00:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ/9HhWgZqeaB4FrePcfnleqIFw8UUrvPJAX2lswGKVy/Wdx
            ypsXGIGJJlpSEXB5u9GgJCV15FpPxGcd4mhy7UrhiyV0FxJROxYOOOo3/SkvVWBr
            ze+v9tkGavHoMx6SarxM/L7tYan5b9fE9VnvJZ9GzHkKmvjYJA6TzHklHfwpZg1b
            QuSE7EGBjPwqUJkqsNX/Jm9SQLaaopfAr1v5G1gCQBxrx+/N3rdntlyVftBGWo/8
            Nl3yCb/JDwEQ4NHWh3tyRZST+3WTlaj267BfdahwSIHjBoW9s2/SOk7NjqG6SJk/
            /U2smIiUEptcZ8jFzQ+MG/Si7UEwbjoekRkVHRSHQ6KSnDJaauFf0RLIfwNPFce9
            22NR6SZljV2lu76YqMi06b7qIzwnMyWBVB3UsH1pkFimHi5pMR71LERD4Obgq4qw
            8Y0MQE/OvBEoByzFTKhjJ+AJzouIgreG3HHYwUW/0g7GfTN18GYW8Ckr0Py2ls9m
            YyUImLzCgsvlboMkD9LLc05RzMKeHLsz5krbOBdLc5Pp4xYLSyZRmlVCk4EVYLy5
            pEpOAm23YzFzacgSB9gMpKlNi1MS4nIb6KkiVpPs985A5oFWttdtLWcMRR2HLi/O
            0WOndkvCW9yfBK6ECoE10jjsqWlkgECPX8J3JRcaJzn1DUVwX+A3mE7289UKW17S
            XAFsKhLcxs7svgMAUsuuexA9Q+NsJKGQTCqP8EY+8qzQExS5SgcqH0WdGXkniNdx
            O5DpzOSDGNB9/URTo/rLb7qTtL2uuGMWNMuhiU3D7SVhavkuzl96apAiZliy
            =vkNb
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2023-04-17T03:00:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAket93SDoEtjjtIAPhgmo/PKwBbA49pJ007s7JUa7a8Uo
            ZEO6SMZx0gY0wduOg35iU4rOjWnkA78CIMaeuS6bFP0CH8uN0XgInBrG0abybWwQ
            DuGv7pSXfM100Bky7TFseHwyiwAPnY4qqPpsFshH0CYd4dB9xjw61pEkjpsso2QP
            bPc4D1p72K8XeHsUs2VSep6G+E56lNWCM1eexZIdXoySzlLGtNUMZXLIvAuvl9NW
            AV37egk8jw0ox4zoGLMXxrO70PNVy7mxT4rOqMBGdGCR3YTq0BenoMk4GnIcE7/k
            YYW99cl4tuo4AGv1Nn6MoWvHYCGwfjHMmEFL79eOeoZH9Pv8UPpisvnQUds3G8xt
            3m/WqY6ZftYYESTg02wj89ElLyY90DSvNThAiPQCgTPp45zfFGCyO4G+/sntbKoC
            tttRHj9Hd65LLbqeeQiXpz6N9GRVI3kK6iFLxxSMkEMNVaS8z+0h3PVP8kYY8TWo
            gsE5BmpckA6j3msw4hTapWcq/W43LgZ6Brdi+GEzuZnbQoN/ce8d8C5nyCyT0yRL
            XEe0TgIwAmRGX1y6HbvCagBy3uvsuWl1lFK+3AFwvXjyW2xL+SAmGXv8XsmDUUeT
            GM7vJ047p0rTFPzLtbUb2ggpjOoKda28ECmX6a+AaYWPBHJ9cRs80jsH7S5dsf/S
            UQE7L5WuIU/rKFnAbQgaomcmKP7nsY0NGqA5eyWook6swRl7HA+IfI0dvgABDfez
            i8X9WtrZln2hQuGX7r+jDUlYRE1ugdvjpO3+1t9UJoMpag==
            =PmrK
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
