apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../istio/namespace.yaml
  - ../../../../istio/istio-base/ks.yaml
  - ../../../../istio/istio-cni/ks.yaml
  - ../../../../istio/istiod/ks.yaml
  - ../../../../istio/observability
  - ../../../../istio/istio-ingress/namespace.yaml
  - ../../../../istio/istio-ingress/istio-gateway/ks.yaml
  - ./ingress/ks.yaml