# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_PUBLIC_IP: ENC[AES256_GCM,data:OB4EacvtRE1ZW6n1r5g=,iv:tmB+4oh7H3zwMmTgpJjsUpn0LtwG1KOWpwMDjZVX4S4=,tag:Y/N4P41cAd8PqBGILNHfJg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:iPBkdVyh8JVyhT0Co/7xHBNqWdQBRx0ARez6luUFFK/9Vq9C,iv:8TmNHRAgt0X5gYuPWfaLa04MJIlt8ny4P9iU1CotVKg=,tag:Y8aaG9lGwz0SRgWmLJlOtA==,type:str]
    POSTGRES_SSO_ADMIN_PASSWORD: ENC[AES256_GCM,data:9AyRUOpjDENOeX+pbCSXSG/5XP4tmZFolzI/fIRBj/Iu,iv:0EIN2TRBI67oPEmWeSNqvLPN4FMbKBW8NUa0WbnM3v8=,tag:RH5AaVSfiUczTaLRc3U6lw==,type:str]
    POSTGRES_SSO_USERNAME: ENC[AES256_GCM,data:IBYjd/3lHDI=,iv:edMATXwDcNSK7Xk+/5oEaff0CQT1sPkaVXKxFPeym0Y=,tag:cvXY24A6aq0EF5/Vrd2voQ==,type:str]
    POSTGRES_SSO_PASSWORD: ENC[AES256_GCM,data:fdNi6eBP/eOTxd5s/PLmyHm5oRJsX9rFsesjRN80z9urCOjDldE=,iv:5qFEiXGLBx2X0EefIT/SlAosVj4nKJoJfNKTi2mYYao=,tag:zf6qgG8HXkB2vS8D/pIGpA==,type:str]
    KEYCLOAK_ADMIN_USER: ENC[AES256_GCM,data:lwAPnzgeSA==,iv:5Miw1i6+nTuP9hjLF819+hN43/LvkDQnb/dcGAyH9Bs=,tag:axQoDwZglHdbmMf+OJ57qA==,type:str]
    KEYCLOAK_ADMIN_PASS: ENC[AES256_GCM,data:GFYp3PyRYePwvWQFajZEf1qlQ6Z7PJJiIXIInLqK,iv:SV9a/9u/rP1LcDV+DaxV0PAE9yCtwDSWPjUV1QYj6dE=,tag:WNI+e5rVXgRxt8ABmJ5Ogw==,type:str]
    STORAGE_CLASS_SSD: ENC[AES256_GCM,data:TKqcCpu5aAOmLA==,iv:4UJhOGkquIAwxI0hBxuXEMsAfX7EW746ftxaCZqEf+s=,tag:/wC0K+GU8e497etX1U3HvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-27T02:02:01Z"
    mac: ENC[AES256_GCM,data:A/CTK+k8O3TbiRh8zdoAT0u58R8bfQwrCTiBmkl3n12TXBBGX0R349uQz+5kWdSmmcQ0C4zQVeBIg6g2+PkL5qtSp+t/WfGR3FEdQOJFm8XQBfDfh2Mw72+TaE0mN6DVDK+HlybUCsNkyXPAtyxZAe6z8mV47AWJJb8GV6SXvmU=,iv:CAoYgzEKL0TnKCJlFU8ceH5T/I8lACge/wTW43oodpY=,tag:IQFQFEhOFxcz5FdE3dy7vA==,type:str]
    pgp:
        - created_at: "2022-10-31T03:56:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAApZWSd8jJJzoT/JemudIB16tmpoZ3CD+J0GdFUG9bQlt1
            lWL5MvJbju1ilRKkKQxXZwFocOxm0WWK7ilF530Xk77PyH+M+tpCTuA2XAXcf4gF
            m0xUai3KSc8suXdoQMkCEorVKx2yWJG5xqz8vxW8QJnCzRShpZzyERWoTKNe5SZD
            Wr+dDFa+Wh5+Rpa1+T5MKEOPCflJoV6SpviZJt2N8kjfeILbmGfxQcFuUIZY5Odi
            /l8JvMQy/Pt4dMNBhneFGpia5zdDMegh3+08kyjTRK3chOwrNi4ESaV96JWrjarj
            56yrTnviMm5jcpWPD6iE2lvyv4Cn2F01Hx5VFhRZo/A4AyXRgfjGNASVgmBZlr1V
            ERR6WcWFgGenOIsIpD0ukNrR6vVCfvRUtqfOzh0fjvGV/oecbfunnHlbwDxWPCSR
            gGXsIX70VwZFQjyazgklOtNn3ENpcW9p8T8fF8UAKGVAa6a4HE59e3pQcKT9KgtV
            a/mp5xvbyWic6ygAxg4/OPRu300CbE5smDPyDg+wMqA0edW2L3oSmmTNZFd5RXFf
            qurpDeTLXaKCCv+4MprHBDgVyx5ttaTLNR0Q8XRBcwm9ibf7rpGXLVAUAYN4sDIo
            O5AdN4bX7Ypx7ETupC+GwZ37mrEj9En19NGRKOl+MIPpDr7m3RSqBR/1FcjLQkXU
            ZgEJAhDH2xiax0ytl1spUfQwRFTiLUyM/XalMoVgSfhvm3PwXfSFL6FCxEse8gxq
            PRWPeQzSJOFpOwCOD7fuQ3ehgsy/ddkW8AcNX1Yz13gfdUn6Z/fNQ08o0hJUCyik
            nf3ntNf8Pg==
            =h1hj
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2022-10-31T03:56:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAsujw+kf0q/rOD/unk2ujiKb6ZJ3HTFpuMFDzgDNcpJXO
            OGEzBZGzhZt/6aYmUk1J3hozC+O8HQ06kp1Xh3//rxFIo6ywlKMP8B8+XKSeeYvB
            DIxoJnlaED8nKlb/6Kt7SQapYjYqz3HbFv/nCO3plbTFQ0oI0zn6wct1YkS7pPBw
            AUPCdZuVzCXgIrpaojYUl+Tamv9UXk7sg4uRwohfzZiKNiVeDKbmDF5WylQCLx3e
            /dAP2EwZeU8bjGR8gCHo7VWojb+UhxnuxeuJJpFaHi1Ha+tXl4M+pwQQPr7ZP8Ua
            BaiZoV11fooIEPoNEUJrl9t0t5H965kYplF5hR67DvMWoCd1k2XF4Cm5UjApo1Ak
            L8evZbE3JA+Wz50bGYUA9lQFhj3eHmrlgZo3sQZ+ska2selzKoRrfm2Bby5nt76m
            7Eg7i4FTda9alEQ54COQz9bdoNx0dj6Pc4zy5TlvBpb6fiwOpYqDlME+ZROtbEHd
            Pe99NXHFfqTUFMLyJU5Ye0Ki1KRDG3I+RRCA9jd8QUdp2xeo9CqGj/A/LbS8u3/i
            Hp3aTpXr4kxud6gbYwDLPYogCoQtgpHyz4gQKPkYKHiveEAPpFL5iPMW7E7FYCNe
            FOr+qu3aZIR6xsvl/69zmkv5hr4AyhGJEWeKwhvIfuRPxl7hZ9Ixhps3g7x5pmvS
            UQHAUzomMNlpRC4WdRBhNZusEiZtl0RY7IVzX0bL1Np0qtR6XOkTlXVszM1eYYqK
            4zyFVYVyNgVN1xsTFQ5WGTZSnO7q51PR1MT1vjgTOyHoig==
            =L8Vq
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
