---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 30m
  ref:
    branch: main
  url: https://github.com/Ryan-McD/k8s-ops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/clusters/cluster-1-cloud-oci/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
