# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    METALLB_INGRESS_ADDR: ENC[AES256_GCM,data:tgNMxR4pMSRCIyg=,iv:A/mt/3ELnjpGOg4sy6Ct1Z9AhiOaA6FV/ClFN3J4OCs=,tag:JXd1NDTFLqhFqB4IJ8TWuA==,type:str]
    LB_ISTIO_INGRESS_GATEWAY: ENC[AES256_GCM,data:arP2X/R7i+7fe7Q=,iv:/+P8qwRrYXTLIW1vQulXuaE8Gz/SZ+qLjGFi/tV2yD4=,tag:rrjxdi1xZF7J1GnxEY3hjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-30T02:48:48Z"
    mac: ENC[AES256_GCM,data:/UR9H3zgC+R93Si3r/eiox5rprMdaOj8YrA3zNuagiMYKRhBaA5hecTkkB/svbcso3pcCFkIhgmJZ1uAT/pi61I97PTVqjRNeIGvO1xe3pX7JG7udewZijdZpV3Bav7cF01SGZw85FNpkoKMXl8yZ3lQoeiyqXMpvGDzlsH7bic=,iv:CT5Plg8YOQsodynciD0JZnnWEv8JFQ8t8XqkDsl9DcY=,tag:N2kLYQgy1NV5Mi61tceVQA==,type:str]
    pgp:
        - created_at: "2022-10-31T03:56:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAApZWSd8jJJzoT/JemudIB16tmpoZ3CD+J0GdFUG9bQlt1
            lWL5MvJbju1ilRKkKQxXZwFocOxm0WWK7ilF530Xk77PyH+M+tpCTuA2XAXcf4gF
            m0xUai3KSc8suXdoQMkCEorVKx2yWJG5xqz8vxW8QJnCzRShpZzyERWoTKNe5SZD
            Wr+dDFa+Wh5+Rpa1+T5MKEOPCflJoV6SpviZJt2N8kjfeILbmGfxQcFuUIZY5Odi
            /l8JvMQy/Pt4dMNBhneFGpia5zdDMegh3+08kyjTRK3chOwrNi4ESaV96JWrjarj
            56yrTnviMm5jcpWPD6iE2lvyv4Cn2F01Hx5VFhRZo/A4AyXRgfjGNASVgmBZlr1V
            ERR6WcWFgGenOIsIpD0ukNrR6vVCfvRUtqfOzh0fjvGV/oecbfunnHlbwDxWPCSR
            gGXsIX70VwZFQjyazgklOtNn3ENpcW9p8T8fF8UAKGVAa6a4HE59e3pQcKT9KgtV
            a/mp5xvbyWic6ygAxg4/OPRu300CbE5smDPyDg+wMqA0edW2L3oSmmTNZFd5RXFf
            qurpDeTLXaKCCv+4MprHBDgVyx5ttaTLNR0Q8XRBcwm9ibf7rpGXLVAUAYN4sDIo
            O5AdN4bX7Ypx7ETupC+GwZ37mrEj9En19NGRKOl+MIPpDr7m3RSqBR/1FcjLQkXU
            ZgEJAhDH2xiax0ytl1spUfQwRFTiLUyM/XalMoVgSfhvm3PwXfSFL6FCxEse8gxq
            PRWPeQzSJOFpOwCOD7fuQ3ehgsy/ddkW8AcNX1Yz13gfdUn6Z/fNQ08o0hJUCyik
            nf3ntNf8Pg==
            =h1hj
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2022-10-31T03:56:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9Qs/eFVrZ++ARAAsujw+kf0q/rOD/unk2ujiKb6ZJ3HTFpuMFDzgDNcpJXO
            OGEzBZGzhZt/6aYmUk1J3hozC+O8HQ06kp1Xh3//rxFIo6ywlKMP8B8+XKSeeYvB
            DIxoJnlaED8nKlb/6Kt7SQapYjYqz3HbFv/nCO3plbTFQ0oI0zn6wct1YkS7pPBw
            AUPCdZuVzCXgIrpaojYUl+Tamv9UXk7sg4uRwohfzZiKNiVeDKbmDF5WylQCLx3e
            /dAP2EwZeU8bjGR8gCHo7VWojb+UhxnuxeuJJpFaHi1Ha+tXl4M+pwQQPr7ZP8Ua
            BaiZoV11fooIEPoNEUJrl9t0t5H965kYplF5hR67DvMWoCd1k2XF4Cm5UjApo1Ak
            L8evZbE3JA+Wz50bGYUA9lQFhj3eHmrlgZo3sQZ+ska2selzKoRrfm2Bby5nt76m
            7Eg7i4FTda9alEQ54COQz9bdoNx0dj6Pc4zy5TlvBpb6fiwOpYqDlME+ZROtbEHd
            Pe99NXHFfqTUFMLyJU5Ye0Ki1KRDG3I+RRCA9jd8QUdp2xeo9CqGj/A/LbS8u3/i
            Hp3aTpXr4kxud6gbYwDLPYogCoQtgpHyz4gQKPkYKHiveEAPpFL5iPMW7E7FYCNe
            FOr+qu3aZIR6xsvl/69zmkv5hr4AyhGJEWeKwhvIfuRPxl7hZ9Ixhps3g7x5pmvS
            UQHAUzomMNlpRC4WdRBhNZusEiZtl0RY7IVzX0bL1Np0qtR6XOkTlXVszM1eYYqK
            4zyFVYVyNgVN1xsTFQ5WGTZSnO7q51PR1MT1vjgTOyHoig==
            =L8Vq
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
