---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../apps/flux-system/tf-cloud-agent/app/helm-release.yaml
  - ./secret.sops.yaml

patchesStrategicMerge:
  - ./helm-release.patch.yaml