apiVersion: v1
kind: Secret
metadata:
    name: duckdns-env
    namespace: networking
stringData:
    SUBDOMAINS: ENC[AES256_GCM,data:16k1qK6ZpCrD,iv:DiunJNH1V/UuXzIDG7z+9f77cV/UmncEUTX8wFBsca8=,tag:QBBC+SBTuOJQ9GOLU6W08g==,type:str]
    TOKEN: ENC[AES256_GCM,data:gcA2farjand7aWhFxJouL4f/vPyySku3RUAUOqmPTp2cLwe4,iv:I6e0nfPiyY0nhMOwFsUX6KlXalW7NW7/3Hb65lbZ1vk=,tag:0HZSdIKBbJnklAazUzh5WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-17T03:23:55Z"
    mac: ENC[AES256_GCM,data:Y3yppq3eWMflsZMEICqPnt9Qr08ZqwN9Czw4qaRzBNBSh497tssE+CdtK22iCNruT22aehescrwtx2Hud/O/C+iZw4kzKJuB3B2Gq6WFO+Hmwl84tmWFQ9xyRq/QX9yXf4M3IdDv8JDqjKE95Tt6+ekHAzq+Iy07M+mV1PuPT+s=,iv:W/JwXwKGc8ngMqF5Jk/m/eEIagmWZXIuueOr4n0TwxU=,tag:ZuTTPspd6j7okCrhJXKoMg==,type:str]
    pgp:
        - created_at: "2023-05-17T03:23:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQAQ/9F/IYsu6su1cbG5NsJM2XoE280Bz0omo+6KKU/HqQesC7
            l4j/UvqseRLj3cbE+0dEEFxaAIMTWUKBAoJjHrjIhEb0AAyTBHoQC/4G3cKTxfki
            4n8mee3to7T5hdDoExJPogFKIZUrmeThOryA2SxgfCHH0Uq+1LvCznrAwwfhnQX3
            InFwLtgVq3eznbYSKwqbdZc3Lg9a9QPJnFddeeF8MHF8aw5T6WcxRwmUnUJYuBhL
            EmUh0LQafauumWGZGGt2ob7ymVk8pVMSxpw1TfwD4T98av7uMraexdJCXwo0Q2LL
            nlTWPjaSZR9gcj7+nn5tz05ZBPGDe0/hOAGPNFdCah+33fBVrNDsReAjTn9o2qQh
            Fw++Tns1T2vOpi87tDx1rkmpOyPLdHYe7Tz7KhoyQUWq5I7J1s6xQi6lXYEahHBT
            jjWydqWL4pygeLVtsj6nze7rdCxDMd3QD5Z+qV6iKutBoDcsRWj5O0fN0p5cv7ip
            KJwJsCghTpyt6rTl4ljm8o54toSWZB7WhDqElRNe0q/VSwNT3IIAvTVKvaWZ5S/j
            nh6b7qP7XYxWgUtfgjtOoTq1BF7lppt044IgbKHXdANw3R8MPVHy2s1BBx2isnwM
            AQJFjye2TWP+EZX+sw2EgiPDJMYpoXeYRk23rzD7Clxog/xaChfa2hFYYuL9+T7U
            aAEJAhCo1c2peTVhV0pfIs3HmSpCZWxR63a1us8b9CgTMRPWRhltnoqVaufGEGAz
            6w1i+UOXFsZptCgcawnlK1Qp/Zk0x2QQy9gBou30BI/e2N2D/veeSUB2V+L74SVE
            SMZH1dCHKkyJ
            =4kCV
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2023-05-17T03:23:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ//awzIx3n5rNwubLJ8/0ZElWV7qMznYoI825AIxOyGePd3
            oj4qdO+o2F25WSFYX9WY/+MfltkzAQV/6EFIA8EtpB/crF+gWTIPdp5TgIgQq0df
            fxYKwrl0/q8AYqRjtzmEg8olVs2TD3RD4VLFLFmXQr+axDvd3KPMYPxBVlvsWu3P
            Woo5ZXJQ0syHln7IcROWccG4wwvicafkHderAh8ic7autxMZ3eI/9xSKcZwjwpqz
            xAQZN5Cz1OZOhh78a9KvKMDWYALvPR+jgpaFFNaB+eN+nHPU68ghjad5DmU3Dvzz
            /MfRBdqlZZhbjSXbdlg+LINPk2sv5Kc2mTM3v4/M8xl8zDte+aNdPH3JUKJa+svB
            Mozi9jirNmkF8m4TQhzPf5VtgDtmo+ITnahH81rfnYfJA1c/e+QDgPNrZqGpbp/N
            MMPAqMD9bV+R7M5oMpAqpQQ0gUsknIz06US5P5iW33oFPNhfLXpkXPxU7X18QIoe
            6NHXHHNgep7Zns6t4vO2P7An8oaw3p1Pc+qbKtw5TJMVXESzYWgdxbbt8mWph2Rp
            xQPUAnlrIRXLsU12AD1a7qCb37xs4Egk7Zp0sT+U/xdaoezpe2O16pEmsKF26H3Y
            Yg1GCKyVKnltPBv3cDlp0nqeY9Ph4nJ9zxYIrBNCvQJeQKOU7Dsc+5vOS2I0tpDS
            XgHvGSnIywxPNy7cZb7rcNs1eZrAQMM1lvm6jN5XBmpJbr+ZEY7FdyFsb7tSqUYt
            Vouz45c/rbSojv6p5apyjdP5xdg2MJ1yB2rZx49FDb7ICGoe9Od9YPxw36zSvx8=
            =mTa/
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2023-05-17T03:23:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++AQ//dVzML5Bzfx4aLIlVvLKG2LmCfDNZvrIV4XTYiJiyODzZ
            zZtAw5ALUiHG6iliVaiLjrU5JgEZDUPyUR5NoeKWz81gCFiQyYyOgqmAj1ALY1yu
            b17aJd7V8lLxeCt5HmD6At15ZoOUdFFNgNVtLyr6A4jVa+3Cn5LpIfZIhuOgcpnh
            PtL9sAE9+OOxBS93gikbFTGnKGAwW9Q76Cb97OnUWNUUX7u1WfQctRfMayyqv8b8
            ad/i5U/WURPlhessXtMMUmFSkf1kPGWqzI5St8IKz3LwZO88cygGNa9oLt6ZV8C5
            SAtg65o3TT0VoOmEaFogLlcVESmY3aAzICpCUIy95ifx3GqIQghmKy3Wo25H1zro
            SyByoGkyEYp28mI6jrGS3uoOvjTZ6J0ILYbYZ4Ul9xE6sirdbww4Z5+1eg2mmZPx
            g071oKG6AVim1XCWj1Dug7WyUeVIaOJuF6CNNtWVr29wdodzInEyWdssKHuODmWz
            yho8rK4DS1nna5ir6ozgeBwjLjcWDgSWR0A5HIkFovcLX0ehA/G44yp2Uaeyfx8a
            rAIHy+e8lEL6IP6UsoCkKAWWp57iVE8JCH4xUVbX61JtY07XKpq8oaXylfAFo+n2
            L9iFfqC/GHwWNAfcbt4UQtpzROiiFmuKvfeVS1OCWmnhKJXTCqfkx/8ZXTICOgDS
            XgFke8kJvansCSY/xmIKsp1In4c6HsudxAFRP5MXnlsRSQjwXeCa8gGRKH+9Fg3r
            dra3obHAK6lMatkVXW7BxrydOWEBLG/Hrh1sOCTaK5tDCboRR+N4591f7NLtupI=
            =69KJ
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
