---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_1/./-}-production"
  namespace: networking
spec:
  secretName: "${DOMAIN_1/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${DOMAIN_1}"
  dnsNames:
    - "${DOMAIN_1}"
    - "*.${DOMAIN_1}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${DOMAIN_1/./-}-staging"
  namespace: networking
spec:
  secretName: "${DOMAIN_1/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${DOMAIN_1}"
  dnsNames:
    - "${DOMAIN_1}"
    - "*.${DOMAIN_1}"
