vault_root_token: ENC[AES256_GCM,data:vsAGB1xjSWFBM7i8/pc15cJmtNkSOzdY/nJeOg==,iv:BxemqIAdRRqm5MOLsIFcNIkmd42QzfAtjy2BDX1zC7U=,tag:s93nPEvDQT3cAoDUCX3odw==,type:str]
keycloak_user: ENC[AES256_GCM,data:1fBtKifdKA==,iv:TwbRJJvDfU2Mtbw7bgvbY6N4Ok54FqUhUqKz4+BNDOM=,tag:9GYWOqmh8n5BQzoziyFIZg==,type:str]
keycloak_password: ENC[AES256_GCM,data:3W2rhJCWnZld/nCcKeEmR9H7IQmukynvWp4qwqmr,iv:FT6j05LZBqZNHU2nNrzrwg1fb+N/XeOSzpFOLZPBI5o=,tag:um/QCX+3j/SkqJruzy80UA==,type:str]
keycloak_realm: ENC[AES256_GCM,data:hhURX6Ij,iv:p1VwMH2Hr09rs1qPSivSS80wqjLpHKh9C4fVl6Qquqc=,tag:+e6l2OxXMR7x2FROuws4ig==,type:str]
keycloak_addr: ENC[AES256_GCM,data:8MD8mB/xVxgoJNN+ierkmA==,iv:APd6puGupsaLaLwXm6m0V03EwuwZGoanYatFSq6s3co=,tag:2VVgoGVE4Q7ecJpISeTp1w==,type:str]
vault_addr: ENC[AES256_GCM,data:ARxmU+WgF3ee4qXNEZ3LOLE1xQ==,iv:otE/lxsr+gP8Q+afGw9Wa0mI1wT1g80ZNbHif4YZ7gA=,tag:7Ab/5JQVm6nPJNTEAu+0eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-05-22T02:17:54Z"
          enc: vault:v1:bDWRsITIoqUQgaADbysw45J4+ZYsyhg+EsmgrR99Ql0rTnTA4OeJWSnwNeocCaC1Mb68i92ys3FCW/pV
    age: []
    lastmodified: "2023-05-22T02:17:55Z"
    mac: ENC[AES256_GCM,data:APAoa4qkLaPkuZ7sn1GfQhIpiM2oWOs+naMlgz/MHvtfUUAfLSWZbK2/ndsRbXtHMQR9Eiba/DCoJpf9bzt12giQz8H9Jw+T3QZ8N7zy/0V9jRjClB9Az+QzgRy/GASJ99aznfMOWH23qZtIB5kN6KXIdEkBL92WDUjLzqWD41c=,iv:UNCM0w2x1NGK+DmWLYvlw4LAR5rXl1XVWoemptbpNGE=,tag:7qLIjnssiWsMq4eUBLXilw==,type:str]
    pgp:
        - created_at: "2023-05-22T02:17:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++ARAAvrfnTOqAd2S99xMhmOVl/F7DTYCYNvh+yeryEmxbBlWF
            uXjX8MIIhA8Z9aeOoxiFIwVDByp9YFVaRpTyGStEEVJnc3ry6cArSlGrLstPs++2
            VRbfjwJq5NjC/XNMEw8BK/qMnuDqjtDg+Bl9XIWMj100qjV4ZPk4MaJkt9crxt8+
            V/SIgZp7p97TFQG8zWPOuxNjowm3Hyqjk4WifFxMd7p/dAti71UWdOi3rv3cFXYY
            2DGnMjCJWb674RGHR97MIPS3dLmD+j4Wlu/T+sSPgWbyNz3FN8cp2xnMxY5BNSgZ
            K5hyN5yWYgAw95qTfXSHyF+TZ23T3XuZHP0lcQVNhJf1x57EYeLpjvU2TqNYl1pk
            n77fXPgHBOhMbzp+y72OBfBkVTsfrjkXMZoJ4cMS5D3Bln1RQhKTgHXjDHriQJ6h
            HfbBvjuBfFgB81gtYZ9h2yMmT3/WRKiKO97thIqYtoZgbYgjAcPBwjCrdSfHirER
            /i15rmsXC3TstXRS6YhSLaIuOsUPFUfrPIcyIe/KaWZTnS5lFU/TvXKSUsp5YNFc
            b5tzmOTtiX5TygpPLrz88FRErvKfffuQXz8W2XL+kM7hn80Cfd58Gty7j+LRsWKe
            JKEwE3Y3CT+oEPKjDCnqVsnD9ljL+u5VRgsMnjsamTlWY9AiHV55WxoCc3xxbBnS
            XgEkIrAAVfsbe0piA8euDuAfGW5XYnXcGLaGBE7XXaqLq51hDFgO+QhRZFXJzWGQ
            HlKezrtIRo6g2VKDFPUfIkd9xozzQPB/OiXcgzRFfgJ0p2zMezzba6QLyb/fndY=
            =e9zl
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    unencrypted_suffix: _unencrypted
    version: 3.7.3
