vault_root_token: ENC[AES256_GCM,data:4vDSTOQhwbCmyLWM3IU8uAat+g+UY1uKNO/oRA==,iv:nJpXAapNU4VeB9hc4ZGCxRWklbu5/QNZLsiLDB9a+cg=,tag:WHItjnuXaCfiQHZ1dAbD5w==,type:str]
keycloak_user: ENC[AES256_GCM,data:v0oN9nPgHA==,iv:m1MnMin17tka1Mo+NN/CsClnJN9RtxK2CJ2WqMI/lWI=,tag:/Kv9KAcNgZReRq2fji74aA==,type:str]
keycloak_password: ENC[AES256_GCM,data:rdjiBnHM52FjrgdOqu9YZROVoN1gQ9nTPiY9GmeI,iv:41tpo+ij8i5WNuYOjbkEhEvSW1mjbY8XyngbyR8sv/c=,tag:Cf7Weguf+lXvXyqPHKzVXQ==,type:str]
keycloak_realm: ENC[AES256_GCM,data:hOEOggig,iv:mx0q2iXvgHcldtI/simVAh8mD5UVKmnz4NOY6PTvbiE=,tag:iTJqGJHbL5Qe8ERJRlhnnw==,type:str]
keycloak_addr: ENC[AES256_GCM,data:I3Y+KB9C/gizXRArPHFBbg==,iv:d9y2arB+qymZy6oP2Vn70bu4WfgzEPM0PUg69jPzgvk=,tag:2n3XBXJaHZK1vB1bKc4cJg==,type:str]
vault_addr: ENC[AES256_GCM,data:dzL2mGbJTrC6QgNIrZIRsfeVew==,iv:85XNPMy2rVL3sGcx0H95/CW4ZVi4sltS3DhXytOfgXc=,tag:/g52Fczv6hHQPRC9LkIeQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-20T13:25:04Z"
    mac: ENC[AES256_GCM,data:2+3FD3S1Rm3aBIDmZg73Joz0dE+1du1jAsedpmQgQCW0jvAOwIXmJ1/hSJuyXs+J6hVYFoFnHh7jObHkpFfkBcK0bBiyIhuMMMqyVRk7GaSdxmQXQLcCQ/oO765bMIuFJiVxg2YkRDfPssQPcV5pdvJYz/7QUQW8k2REQHiwCCU=,iv:ULHcV+MCKB5jYuI9SpkwGJ1Pk7+hZbwEYAzRUBmiFBU=,tag:+59fWOdGT3JWbSvzB79AhA==,type:str]
    pgp:
        - created_at: "2023-05-20T13:23:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQARAAjdYv337rz8dzuDG95gvTOfU6G+iNKSmbJuYd1C2x88+U
            9xKsCApmpr7qDLYB0+G1VTOuXJ+pxrAEsz6yv3gfv+Wb1IiIYcI35ltxoCh3QqHv
            W6VykxuaJSezPhr2hAIwoG27xwXGllqZ1cKMMsSBM3NkoexCIsn/QbC7VNj4uW4h
            fv1OuMWxjxllXkVNjDGhf4ybWZIIyofGq4OmqMbeAGWdkG6lICR8kfGoMdGOtWf6
            sUJOjjiqexR1tppKIUnJho+/vCAOun3T9NfP6Ud0X3lLqy7b+MZH8Id92OB7mr0w
            MgL3+XX0/5zuVQifyBP1u71/8Wd2dUW12N7vba3zIR4GX1k5bYMalu48E8e9hyjr
            qdpX6jkywpuKay36tjkmb1lhnkqcLhrMG3SIT+M3MhgT3j4rtylcsyrOEXJdEPVi
            z9J6h3zGvitYjbQFL78bbCbq1Z0Bu09kRySAdpwDfbXakfpkOUgvkx0/3MrMraqI
            jBZq+rjIiuSF/fPLRpaXy8umerilJ3b3Hn/S7yWoyN+GGIKnD3n9BMXzkx05QDoZ
            hjItR6acRNrKqlRntgnBMg0H7wNr81yZ8p9ZF+e/Ix9xFpxxNK+mBwiNWC5vFCf1
            fhZUFwmFylevZn4xrtAPrkw2G2YauNUPohI/PHfQNKVnjpY4P+UAWHamTwv6ujvU
            aAEJAhB79slg7psK+jBXEasKTeObeGhK4LoT3kcMRKEe29MB6PRgg2oGcV8B6s9O
            IlVqK8HXXULmuYGGJiRas/XNoICbofvYPnXTpEpFfpodfbTFP980cxi43mcYKlMT
            nTzQo7KQQskn
            =dDaN
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2023-05-20T13:23:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCARAAmrFwg6fdz5BgW/Etpcyq2ZIHTEr8txMKz2gtfR8BN4ou
            Ep+hn/Pou3W8IsZbogRPphmGWp8cbN/iQYLQRV/TeufNLDDOAqIJ+OV7tE6xQSqo
            Edi+G8bcTm5PS/J9fkFmIqgBJkF7zR4szH2EqiDeubJc/H2zT7hVkuMMm05/M1ON
            n5Xuz8wvG4aw5lIpRk1BDRcnQQqxXWYVmMTIDvykSoEZn1ScObnK1Yj9sAg50oQP
            fDTqW+IaPwacRHk48gxx3B4HHt9/9Sh/E0cD7AHC7opabro1HHryaoMhFhyKQli/
            nijel5BkJEGiM/cxk4pZXm21oJ/JWM5rCOLLJR997cBJBYiImYBwJN8Fpx+IUkJB
            QDnJewTO1ckapX53v47dCTVR4UBzza2w2PRNvmAWBUqoW/ZnEsM6OA/VLrCD+1qb
            wnKKPJAvRQ4JYWJ9EhCiCjN8NvhIXVU8goZlX7CTEx+eag4eTMv6gcVG7qvNIVY4
            mrTYvC42RQhkWeqydJAxf8A/GphxeMPMRLMQWv9Ib8oVtEsWVO3OgJn8IJqGyD8r
            Iyo+1sCnThkDEoGpn7a6wv/h5TfhO3d6Ewl/s2Eryl3ThsUngzw43bVsn6opCq1N
            EBqC95lEU0G7itARj4UaHRY1XSmq5edwXTeTjw8ypX3YKnqWcJOI47w9syadxI3S
            XgHrgS0bB1BqqK/nblpdl3DKDFuOLKr4DPCFC8oIxLKoGdtDnVfYTyjxVPUNHZhG
            3xDmZmgsW3N+X3ki8EgRfPLgFuzrUAGuwhKNTKEWHjlBnAStdeIgGsNCpEkigdg=
            =b9Cw
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2023-05-20T13:23:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++AQ/6AppkwePNVExW9SbH3zIYKf3wCbtxfy+LSlLeRM6Ivhqo
            RuHkwX2iZEOXGTRNtCx/9zyFdHgxXMO/R+yISk+oWbktWf2o0Q/n+2Cx2CJ8qt2O
            NB1ZHc77aU1SDWZJ/oj7B0SPTJEKz7CDgxOykjNvom3x1G/kRZ6if+HUYx/tM+8H
            2oy1VfHhG16wrD13lURZlGKaYrPsOPThEc8TF7S0yK1aYNj6XsMJkhCcvI7u153I
            czK+aM45bHfdpswRdZKudoYJIRMPuIKH+Wb9mS3g1MCuy2dqhSPamcuAmQRnnlqb
            rQUSbbxKj5LPw9RViJ2L7szM5gnhnr7ikZkkSj5VXOSWHrM+tzF7K78TQvBAfT4h
            Zyrd959zS30agn7jP7QzcX8IErUzEuop9MUFQyNWQ1wIwpKXmNf8NX12R1u43x0C
            Qw1SQRBHCFdJYUOh5z+YizPXGom8cWv3qn0sTLuOZlnknL7RV0Qxv0uXQ3ZjdX3u
            DSUXxJbF4TFvMNohKrx1A+olj0YjfDPd0BVVpkZbqXc4ObA/nV1Y13ssSvzy8d5S
            T6L7U/pbADf2Qtgsq2Bovegd9jGfAHUXKnerXXf8UmPnv2pHPwSY6Xe0bXn2ZR8P
            Z3wV46l//vSHfgajU+B2z8xBI6r0LhyESvLoNlGRy7kF7wRDX6uoAXcwrnHVm8XS
            XgEBhuedVLQN9JUsXeltCEKo/x18+4WthuW3FcGAanJ8Q/0e2mwNGSy0R/HWV2hS
            HvARSp/jmeNXbTn4P2gNBXPnVFK2u0d/+LhhlzCTmyZ942MnP8ZvH8CjnB88dtM=
            =UqE3
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    unencrypted_suffix: _unencrypted
    version: 3.7.3
