vault_root_token: ENC[AES256_GCM,data:A3m7iO8Tpnz/mrMqgJchr14ktZtcD1ljvYorQQ==,iv:5/vKo3rbYvafmGbXogdPihy5zl0f8Vj3JOq1p9nfewA=,tag:x+sM7WKFbDZrBDF5Ai0Pyg==,type:str]
keycloak_user: ENC[AES256_GCM,data:y2Hf/BemBw==,iv:RJ4VDUP1K+8+mMPIT3Tum+coidSxiWjMdJ+yfMbiV2E=,tag:XlYsNT4lBNWk0zRTSuo5PQ==,type:str]
keycloak_password: ENC[AES256_GCM,data:i38Ctz3ITfSbjVGgvkXsZ1LBTQFhQF0olUl2FaG2,iv:jqecbfZ5fcGEno63lp6kk1pg4vnJXXW27xDeqNPpgkk=,tag:ct6E3OzpRv02+zIV1oIgjQ==,type:str]
keycloak_realm: ENC[AES256_GCM,data:81VW1jp5,iv:0400Wi5vlOfhxUjYIxZhmMdJLYeRjAZ6WkcxCwVfNnE=,tag:63+PxDFfm9Xfp9uMpEVUPw==,type:str]
keycloak_addr: ENC[AES256_GCM,data:u+KGgFfWDTdsepa3L/yscw==,iv:NFzXCJUOVSkckBam4qRie7EhW7BMLLzPJMmpPjLujGI=,tag:69i5ruokMGBGJjpeb3cHOA==,type:str]
vault_addr: ENC[AES256_GCM,data:bYg+52cGsT+aRnUqU3ntCHlXFA==,iv:ERv1Ayocb+6wmtV+PIPKhZ+nH6zS6e3AmmLm6Phjd7Y=,tag:T60zQmO0NfJpCJmcZV6Dbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-06-07T02:39:19Z"
          enc: vault:v1:D+5Gg5fvuvr8Xs0rT5rioIItgIDEQdS3+u95sLxKszFowsAYAZ01QxMygyLGeLdipMPlTSZWwAHtSbK2
    age:
        - recipient: age17nu5r47gk7y79vtg7zmnrxxedxltm25t8wxry3g73w7t844mqs8qgh96es
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN2g3Y2pXQ1Rid3REL01K
            d1RmSnE1bHBQRlZHQ2hmRk9IcTBiUUR2TTB3ClM1clJxdElMOG1MU3Q5eG5tbTBW
            bG1rV0xZOWZEckF6cTlYOXhOVC9XNlEKLS0tIGkvdXFCb3EwUGpNek8yQjlBd0do
            ckVZSUQzTU0velZZVnloVTdSUGhCRk0KWvB2sMhHrUHF4VtLMGtpQp2X6t1CnivW
            +LN1UuQYLwRjgZ7VCKAsDoDiBP7imB0wGB43675oplOZIJ/rwmyOig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T02:39:20Z"
    mac: ENC[AES256_GCM,data:Dc8kdVOtOI9yaoSVtDEFB1z/env9RkHH7CZmnG4bdu2ZkcmedhO8YPjD4MgGtd6JikrYb621uTxZSqw291Kj8PVT28VUjbUaQZ1q0gpKXkdVgr0h+YXlg9shQsKTCG+XyO40z8AqPyCvJO6VXKkzJuqr86IQDPeOfxdZN22HNgM=,iv:8aQucjSsjRpKL+sJ5rpFme8KSyfRn+zpLI054LA+NA4=,tag:lC9ivuQN6hsxEDgw5Osvdg==,type:str]
    pgp:
        - created_at: "2023-06-07T02:39:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA9Qs/eFVrZ++AQ/1Fui9MTDhxSp+qsYMc4Ijvr/b7ChkKzodxB0zQqB0+PrG
            qRLlWd1PAEI/EED89QjOsriUAcsZFqwDUphiteK7duSFuUCTyhHBvz6BrQgeHYhd
            DIPhHBouYTwbuiy5SlakkvBqgVz4wfu9DR4snF4oGg1hEiekKvjKRAXl5HqXrTjC
            M/tQ0iIgLDFzApBpSiE/t4f45133KmPJpc34c0W7CO8aVO/+By11sc+h93wleWJi
            zmbiwwifv/tlvMh8uBz7yXubyz/NhQrQ1YdpHuiW8o16Lqg4P6zr8Z5UcXZuv5DG
            dYxd6ALyNEsOYYMilikcWmVc2fH9tUWClkmO84MslLpTNOIbezlVr7v24BBg99N9
            xIkwd91odSyQ+/ufsKGryAZnyRZ+KAbL9epfAQsR5vMfRwNEEVyI14QTG8K5MvqR
            rNXQhyP4ts54CipmcjVYd8Vehif5zeFICLKiby0YoEHUJgFSgUf8IWlOaX9mgKam
            E10QRigxjSASmgaV31EqxVyFux0l1+cUuYFeo6xce3SHN6IHgUfKgJ6Lc+OLMbgZ
            yvzx6CgJlShDzyvCCLN/5tbbpBVvIVC0mO7yHxNZb1BUbr5+WBjuW3JRdtRvZWNJ
            yS4BYBCc8hSE7EEFQg2AJS2w2uMX0wHW45tFR0mTv7yNa+XLCeXBYA/rHBBpCdJe
            ATfjVb0625f7JeO0HQk38V8Gt1rreb6wRWjO9VmbSCry038TaEh5ndipUPpQ7uIT
            FEwWWGniz8OrYP0p69KoMemnb3tAzClMGV8Dy2ZalEZdXZ+ndze0YVA0T0ohhA==
            =Pg+w
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    unencrypted_suffix: _unencrypted
    version: 3.7.3
