vault_root_token: ENC[AES256_GCM,data:A3m7iO8Tpnz/mrMqgJchr14ktZtcD1ljvYorQQ==,iv:5/vKo3rbYvafmGbXogdPihy5zl0f8Vj3JOq1p9nfewA=,tag:x+sM7WKFbDZrBDF5Ai0Pyg==,type:str]
keycloak_realm: ENC[AES256_GCM,data:81VW1jp5,iv:0400Wi5vlOfhxUjYIxZhmMdJLYeRjAZ6WkcxCwVfNnE=,tag:63+PxDFfm9Xfp9uMpEVUPw==,type:str]
keycloak_addr: ENC[AES256_GCM,data:u+KGgFfWDTdsepa3L/yscw==,iv:NFzXCJUOVSkckBam4qRie7EhW7BMLLzPJMmpPjLujGI=,tag:69i5ruokMGBGJjpeb3cHOA==,type:str]
vault_addr: ENC[AES256_GCM,data:bYg+52cGsT+aRnUqU3ntCHlXFA==,iv:ERv1Ayocb+6wmtV+PIPKhZ+nH6zS6e3AmmLm6Phjd7Y=,tag:T60zQmO0NfJpCJmcZV6Dbw==,type:str]
vault_id: ENC[AES256_GCM,data:EJi1wJBbsV9IRg==,iv:Acag2RQNJO9qjfsH9HFpWiawIRQCUPyFEdwqgzxr9sg=,tag:zJzolo0IrRfxwPknOeFXaQ==,type:str]
vault_client_secret: ENC[AES256_GCM,data:L+Y6pR1X2AJmHR+ZNcF5h/Q3TtVIUQmfmDpdhJTKtgc=,iv:C4KZl7coMAi4oNXSRh5ZdvF18TTI8goYBPytEL9JpMw=,tag:h6IIa3m671AGiebJ8NVG9A==,type:str]
root_cn: ENC[AES256_GCM,data:+F9l5E9ZB0i1bqN5hA==,iv:nnWCTHqW43uBR4nhmgL/RkC68215v0ji9TSPTaGU0oE=,tag:DFotnMTllj4/GswUcvW3Bg==,type:str]
org: ENC[AES256_GCM,data:NuM1Tq2v49PXi58=,iv:VfdXdu/TQFzdZHfAyzTEEahGUVo2Ly0XPiHD4A2SA9Y=,tag:BvwRHPB9+39vK4iJ9efF0A==,type:str]
ou: ENC[AES256_GCM,data:NVEGQ5b3,iv:/zAPchMKYPSNKMeRq78JIoBHAgOco1alDoOBVHhULGM=,tag:6P1DK/nYYZeMwHhpfvk7dw==,type:str]
province: ENC[AES256_GCM,data:XmM=,iv:IkZ1qaCzw86IjJiU39L0niRDpeFFbjDPXXvGk3RbpUo=,tag:k8Mvr3vgLM7+ZyPyKM+4cg==,type:str]
locality: ENC[AES256_GCM,data:ifDe7hfSlx63fA==,iv:UvcbZL+wLhQwPseHWTomakLfE+iHfPfyTDOnaAwQVHw=,tag:T7IssJrP0TiQzyQ4KY/g2Q==,type:str]
int_cn: ENC[AES256_GCM,data:H0dA/p+rOAJT4ODc/6sy/8FEpegV08nh+TLPV6lmoYERZz0h,iv:YY1fTOuOFG5HieyCooZHHgsyRY3ukb38brxuqmP2OMw=,tag:mn1xzoG15/mE//VHQy6RnA==,type:str]
allowed_domains:
    - ENC[AES256_GCM,data:BI6jDUb8N9ABmbotkQ==,iv:hrZccK2UIGXNhOUvJ/VGzaOw/SjPYko03NdyX2yL3pk=,tag:+uFEfEbl8djH4AlCw/BHYw==,type:str]
    - ENC[AES256_GCM,data:1A7NiBJOcVg=,iv:kThp60jNDrB97e+4b1FPg0xP1n9TzN3DQjudwd4wuzE=,tag:6OWmFTGiQROqhp1EyIaBMw==,type:str]
    - ENC[AES256_GCM,data:nzw1gUoF9g==,iv:yfyO8+qP0lVjs3CVSFWwQKHrvcSs96wAuJaRqW8hS0I=,tag:WXKOJnNiN+AH9T+phR8j6w==,type:str]
    - ENC[AES256_GCM,data:tlVGz/sFqp4e+Q==,iv:P9DNJH6JB0Y3U938Lvrmib6LenhwfR5Q+BgdQs47wXo=,tag:8zAuwUZvQcKBupp8wrIjhg==,type:str]
    - ENC[AES256_GCM,data:grn8pr/yWYHmvNIFmMk1,iv:MAoG1fFXE2cuBC3bsGh309Y+PcYTQSfwBOOSbyIXQUg=,tag:Z0Nnq+4xRJHvvej0402Tlg==,type:str]
    - ENC[AES256_GCM,data:gRynJdmJE3t0lwrPbg==,iv:EOffzvirS3tSDAc7suBBmj4Ht1PTlJzR32OZkspaNVc=,tag:3HwW8uSj9F66LAVUWWtskA==,type:str]
DOMAIN_1: ENC[AES256_GCM,data:jTGZ91kiMZWYXy/ibA==,iv:fp/VGV0INsHWH6XpAHUz07ihYGxVl2WRWIwU/Uh50HM=,tag:JlnO5WKp9NtrQtj+cfPAZg==,type:str]
DOMAIN_2: ENC[AES256_GCM,data:mjDch7tyVA==,iv:nslp8RxOn4A+kgv9C0Hioe9tSPm8xbvU8OwfszXripo=,tag:BUCAtv40rMmIfYDJ3j1HtA==,type:str]
DOMAIN_3: ENC[AES256_GCM,data:ScYBlu65CQ0=,iv:aZ+j2PzUwwlptxJTHBAVXCFjAVsMjJ8a7JHr0OiEcBY=,tag:TXfS+P/xTeA8D7bDsb1Ajw==,type:str]
DOMAIN_4: ENC[AES256_GCM,data:O1t8ZQTdBy//gQ==,iv:X2B7hC3O2KIxBJZmtyQLiPpydT6IhpZ6If92gVYMuQo=,tag:buHLjPUiesRYIoso2I9LKg==,type:str]
DOMAIN_5: ENC[AES256_GCM,data:s3zVIcH5gsXSIiE=,iv:uiEsF7/SfcDFFo/Fn2lUbl2cRHBkzaj+ViG8qnyZnFQ=,tag:HQ8manHZ/zAzgUS7OoqQ1g==,type:str]
DOMAIN_6: ENC[AES256_GCM,data:IwdYRCfU/V4BKshvJg==,iv:olp4Wb7txDmamIvQKETalJmeMIgMCmVvj8F+f368j2k=,tag:SH3YAL+VWnff6sdCQmjQQw==,type:str]
DOMAIN_7: ENC[AES256_GCM,data:rADoXOZhEpOjly+5ZsKI,iv:GNiBMewph7Twja3eLyij944OfNyUdIzSB/WpRjYKC0Q=,tag:euRDnFAfhHtj+ZR4w2jHYQ==,type:str]
client_cert_cn: ENC[AES256_GCM,data:16AAtxT2u+fyax/kRP3MxUHBxM48DtLNka3jlBs=,iv:lwi7hBa8puZSfH8d+RbjH0/kDeT1SjiGSc+5mb7ZIBQ=,tag:7Q4bJJqzjflTwR8TGCQYQQ==,type:str]
client_cert_csr: ENC[AES256_GCM,data:1ebeYWg1ccouJ53P/UOUSde1GDLZPSVkCws2Ua5WfY/cPSSQlcV0p7foxH72IzxBopMWH8AkdSSPOPKwfhm9PGznuEBxJv4heVCpbmr1tcQ4omRWWdRovV68L7N0RfYqN4uXzBN60ukRhcLr1UcLH2gFmDdYqPceTBPyVQM/G9awi9aNgoRm5JKrA7kLVy59mjvkOfni97tZT/bX9KYCnCwAsIscUxeqTDHXMW7ps2RqP3KiadK2Krhtx9vBLn4KSFonv+iwC4Cwuh8JnRpyiDfYLecSsItj1GsJ0wkmLIQg27GgylmS+BAnCIaqx8EiKcan2Uo2EIsJfn/mwzB1lrSZMne+s6E/aG2v89foIu2LNu/XfhpSXq5c3i4NZ0jQWT0YiYNyEpKP6095Ho7d8Qs8HG5bRXfCe2jPWhum80lENUQn9MCsxfvS17JaLJt/MhstmYHUqYtff5cnXSghuPZjGKGlsRKaRDPO8Q8OZVfjRGHsz2wOph6CDIsTvO7Hv8CTYfsNcxg7a+lfcOTqrimxo93vRgyjXooMgDzf8+3yegnHD7hAx/jAR9VFvvdSO/gekVCeGQ3VLuX9oKa06m3LQy3hlIAiMLvUOTNX9MgUm39J8aI4OEmj5L1JgmXe7WHqsf4V2X5zRuuvHi40Q7bkUzDA4T7grB+MI21z29KbXpWHLG+Wi7wlrWjX+WNCUOefndGUod2e/Vgcr013OwxbUOZlXDL3r+sK18GbeD/XGfVDQJK0rMQ1o4MIkBR1W2mZqgai2WJriXdISb5R42yOXLzQ6O0AiN4fu6hg6LM1Et3SD33UTZk1b1ooGn6QtiEkX923fMM08yti3te5QM2qZuPCK/KFJkZH3QbQ/PAdl9c31Ha+Y9PaZCaTq6N3LGKjsdcbiJyfXoB9pm/jNWbsG8yCUt4DJRB4XrGVe5ei1JNn7w3ICQ2MzniTeFnZQiWD1vgFkk3lMaI20IgY+3FjlATXYRmbIbu+dcJhNyzk8lhWBdC94NSsV/aOX4IUNSb1yZe+xftHl2UriwoWAF+2vGDnQ1KGtCfGbdNPUudO7rBOiHXuWZCEAGBDrVF5WNYs09UpsVZ+jhEd0PNOY8HjkV1IWjhtODORVohJOoNjBdIvWlxfelVBHyI3kCnZUhDiXjw/jcYkL3ULiKzEYEmdlOYGeJOpZjyuqUypSKPHMkyqOUoQe2muhU4/bdI5FVlJSvDcepc=,iv:Js8S5lUQvkr+jAT5g4zX+3yX5GLT7EDkRmF7eKona7w=,tag:4LtipiM4Iqy7YVENVqkSgQ==,type:str]
terraform_client: ENC[AES256_GCM,data:WH5Rp1So2r+JwuAnlyjyR/nw+A==,iv:k0Ftyd8lphkn2hy6mC43fczijx5WV+dVYtR4RxaJ+YM=,tag:jt8+89mTZ5vG+/PwrzUAfg==,type:str]
terraform_client_secret: ENC[AES256_GCM,data:fWwdxCycXzu4ToDNkRoETP0Gt1qD1M/OMLdCyzRM+9STcjf5s9dV,iv:a1o285m2pdLfC8Mrdyzo3Cw17rxu8s7R+Pa+2swTMvU=,tag:3l8sR+5zuDfJ0lds1ErJkQ==,type:str]
terraform_client_role: ENC[AES256_GCM,data:v6VsXQE=,iv:I0/Ybo6IUc7mYjcXM9PMWkx5BoYSPJTTzqsNSLc9GmI=,tag:DBvZy0h3lqLpna14kIEvrA==,type:str]
sops:
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-06-07T02:39:19Z"
          enc: vault:v1:D+5Gg5fvuvr8Xs0rT5rioIItgIDEQdS3+u95sLxKszFowsAYAZ01QxMygyLGeLdipMPlTSZWwAHtSbK2
    age:
        - recipient: age17nu5r47gk7y79vtg7zmnrxxedxltm25t8wxry3g73w7t844mqs8qgh96es
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN2g3Y2pXQ1Rid3REL01K
            d1RmSnE1bHBQRlZHQ2hmRk9IcTBiUUR2TTB3ClM1clJxdElMOG1MU3Q5eG5tbTBW
            bG1rV0xZOWZEckF6cTlYOXhOVC9XNlEKLS0tIGkvdXFCb3EwUGpNek8yQjlBd0do
            ckVZSUQzTU0velZZVnloVTdSUGhCRk0KWvB2sMhHrUHF4VtLMGtpQp2X6t1CnivW
            +LN1UuQYLwRjgZ7VCKAsDoDiBP7imB0wGB43675oplOZIJ/rwmyOig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T02:26:21Z"
    mac: ENC[AES256_GCM,data:jo40eGCSuunIywp9hs9guqgWZCFqss8M95cLieKciLvKYBTRw/aN9m6gQhwXkwzQduPUnNpxBpqBWzBNFF/Y32Ss1VKDs/In7A040nlzskLMsKbomOHRyeW9uridCiSuva7V+B9bdTF4hWCw7umckQgMrGna8+P3+a6alconW0k=,iv:S4Ecl6+Gr28nMzfXDtKUpfp8a8ob8TyoI3E+ztlE1ak=,tag:qH8egenJrZ2jUKI2mMER7g==,type:str]
    pgp:
        - created_at: "2023-06-07T02:39:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA9Qs/eFVrZ++AQ/1Fui9MTDhxSp+qsYMc4Ijvr/b7ChkKzodxB0zQqB0+PrG
            qRLlWd1PAEI/EED89QjOsriUAcsZFqwDUphiteK7duSFuUCTyhHBvz6BrQgeHYhd
            DIPhHBouYTwbuiy5SlakkvBqgVz4wfu9DR4snF4oGg1hEiekKvjKRAXl5HqXrTjC
            M/tQ0iIgLDFzApBpSiE/t4f45133KmPJpc34c0W7CO8aVO/+By11sc+h93wleWJi
            zmbiwwifv/tlvMh8uBz7yXubyz/NhQrQ1YdpHuiW8o16Lqg4P6zr8Z5UcXZuv5DG
            dYxd6ALyNEsOYYMilikcWmVc2fH9tUWClkmO84MslLpTNOIbezlVr7v24BBg99N9
            xIkwd91odSyQ+/ufsKGryAZnyRZ+KAbL9epfAQsR5vMfRwNEEVyI14QTG8K5MvqR
            rNXQhyP4ts54CipmcjVYd8Vehif5zeFICLKiby0YoEHUJgFSgUf8IWlOaX9mgKam
            E10QRigxjSASmgaV31EqxVyFux0l1+cUuYFeo6xce3SHN6IHgUfKgJ6Lc+OLMbgZ
            yvzx6CgJlShDzyvCCLN/5tbbpBVvIVC0mO7yHxNZb1BUbr5+WBjuW3JRdtRvZWNJ
            yS4BYBCc8hSE7EEFQg2AJS2w2uMX0wHW45tFR0mTv7yNa+XLCeXBYA/rHBBpCdJe
            ATfjVb0625f7JeO0HQk38V8Gt1rreb6wRWjO9VmbSCry038TaEh5ndipUPpQ7uIT
            FEwWWGniz8OrYP0p69KoMemnb3tAzClMGV8Dy2ZalEZdXZ+ndze0YVA0T0ohhA==
            =Pg+w
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    unencrypted_suffix: _unencrypted
    version: 3.10.2
