---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 75Gi

  storageClassName: "${STORAGE_CLASS_2}"