apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../core/cert-manager/namespace.yaml
  - ../../../../core/cert-manager/cert-manager/ks.yaml
  - ../../../../core/kube-system/local-path-provisioner/ks.yaml
  - ./kube-system/local-path-provisioner/storageclass-ks.yaml