hcloud_token: ENC[AES256_GCM,data:DjCDNg7tU6crWmk2RZmED5Kvm47m6OYbyggu/ry0GhGcdckqccXS+Czs+WeZPX6FiWDEgluehrORzowxosjslQ==,iv:dHnQsTwar0pXPSjZ4DOsBABYI68kgGVa43jUJviFTdo=,tag:eN+hk7weGzHSavU8NreHOg==,type:str]
backend_ip: ENC[AES256_GCM,data:czV5sNrlcYnrF7/b,iv:iwDdLegmh6xEpPPqVeQMRzK9MkiaLFTKJCQrJPCCzcg=,tag:O9AlT3tlIAQ8NV6u1t6EUQ==,type:str]
sni_domain1: ENC[AES256_GCM,data:ELJyYzT1sIOWyFPpf6GqVK3z,iv:EC0J8BFl3sFTq5CyJyVJkuRGPrd0kFb1E4cAxYycjKk=,tag:BjLZysmsRX22QVbxG4+BVw==,type:str]
ssh_authorized_keys:
    - ENC[AES256_GCM,data:EMCLPdKsgj0ViK9Gp2uU,iv:7VneaXNrlgRkNcy4S//OlYKd+8dGlmWN0Ej/mdSpgco=,tag:t296SN5XY07hVYZnPoPOmg==,type:str]
    - ENC[AES256_GCM,data:nJeqGzfb/ulNE00X5+LAZA==,iv:BDMWLzOTb0KVxOdpekDM5kKuSwOgSZKl22aSpxvsQLE=,tag:yiw+PSthqXA7M/O0Pr1r7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-06-07T13:02:44Z"
          enc: vault:v1:WvesejqAH+Z4yMNk6TmR2P05eGohoUPZuSUTgt7O6lf8OONgraSdzghNxxkoLCR9eVVcQYne1JkkUcFw
    age:
        - recipient: age17nu5r47gk7y79vtg7zmnrxxedxltm25t8wxry3g73w7t844mqs8qgh96es
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTi9JQXJtK1ZwRVJ0c0lx
            U3VWeVhzRGhUY1VjRGNtd2d4aVVBMlNYbWhjCllNcjlDeXE0TWxRNUI4Zi80NnVi
            TU03SitmYTM3b1lpMlFKZWpwWkZUYWcKLS0tIHNTamxXVFdEWGg3REZtRnJsUEQz
            c21XYUhaejB1aGlyTXE5SzNGUkFFTjgKDxmKiOZqHkS1ysbUZxsSPpPyG5cKIZyh
            J7bu9mxUHQ5ywKehC75Id7ti8668fueAhlc6rwGD2UmTla3PzX7QHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T12:55:51Z"
    mac: ENC[AES256_GCM,data:D/0gviqrB5Z7SAVEACdoBhTX4W0VWwiKl39kWBF2C+m5H9FPUKCZ2EFau5vrRtIqk4ubVvijRfArmi5F5a9Xblog1mSnKq/EimZ46CxlcsNacJCjJ2UE0oMdy1DyFaBQiqSkOjc2/s87UpeBeG7ZpaslBE/1b4h7Wx8aeNzKlc4=,iv:R8oVn4Cj6lImK+55lNiq3cweZz1thjospxRHBk+wrPs=,tag:/z2Bf9uD4gXwFsMF+U1DCg==,type:str]
    pgp:
        - created_at: "2023-06-07T13:02:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++ARAApTFubzNrraQTfl58+AFuJuTvaMPLLgju9Hu5+lHLe5SK
            /A1nfs0NYrYKrcgu68fEX5+mVWl/q78jypXF6CPYdsYjKMuUfTjpPP8tzjCDvMHs
            KvJWZL6TG8MVF4Hz702wHmliMrwOnRsu1FzIvWeDCqRX55CZvwCw0pfU6SSpy50q
            LbOqANP1CTBbrXnI/O1ptFf+1PDRTwBufvb8BD81mVlChkHPsyU/awOsMREFIeX9
            iIesS7GUSMN9ecGFdj0DsvlUqlZu5V0nfmgAkzIxS9KdHRV9h/GC/BZbYWWxNqX4
            XcF1uwBgpHBeb59dXPOmexjgtVA9+1RGFyYArAvlj8dL1rCFfWrsrMc/20ZWeRkI
            EqEXN+g5yZGzyfUsk9yVYH8ZesANbhwXaB8S+eiw+G26YBWdkjcQNMEMvLyhVB4D
            BPh5uRNpvaNZ3bwyiC6rr25IyMV5AVlOMDlNUEqR7dhaLC1o15uXLPKU+85vQQN2
            GssFmzHh2Zkl85Mm6nGiX6NdcfgGHUcneIFG5y+eqb3pVgRrhmX+ScbUCJrSXacS
            Ys0qDJO+I96gF6qEm2Jq6MuUk1UzX0Z1AYKLXjpgjQ/4kTZO5059gl+7rmDoTRxa
            V73pjs3jDvCRkxHyrlzVYS7gk5Qhcy/NG/QiUZHh0tylFVYPRwO5IelSNNzPX+jS
            XgEhP2Z5QjsAUou6Y8KhKNVHyR26fKHtBMZJjTKQLASsF5lCY/QZ044W4gx56auv
            0TRu3saRkRpE1fUu+pWf+9Ow9NCOYDa83OUC0LyqUrUBaklEZiWHORt6sQG/eRY=
            =Mxud
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    unencrypted_suffix: _unencrypted
    version: 3.7.3
