keycloak_realm: ENC[AES256_GCM,data:81VW1jp5,iv:0400Wi5vlOfhxUjYIxZhmMdJLYeRjAZ6WkcxCwVfNnE=,tag:63+PxDFfm9Xfp9uMpEVUPw==,type:str]
keycloak_addr: ENC[AES256_GCM,data:u+KGgFfWDTdsepa3L/yscw==,iv:NFzXCJUOVSkckBam4qRie7EhW7BMLLzPJMmpPjLujGI=,tag:69i5ruokMGBGJjpeb3cHOA==,type:str]
bind_credential: ENC[AES256_GCM,data:z2MLeI+4UBDwy4vXuvHGj/QlsD3NEeql,iv:MYInj8uiXzTIkEoUEQR2UroTKpIvewqR6ZmdMI1YOEw=,tag:xdZtVC4OSRko9otVbvQj4w==,type:str]
harbor_id: ENC[AES256_GCM,data:Cr8Ds97je8WsCg==,iv:mYIXhDRuLuoDlc4jZWZ/z7A1ujYm/6KlDcCF61QsoSs=,tag:PLcU4Kg0Ioh4zmb40pqoag==,type:str]
harbor_addr: ENC[AES256_GCM,data:tibogMrKs/0HferjTORjFqa9zml9IA==,iv:92p79egtkyQOZJuGkdwn8vd7eUMA/EvVvl6swBCZupI=,tag:zGLfQW9XffewZGaNuQUYbw==,type:str]
harbor_client_secret: ENC[AES256_GCM,data:LOe930oCzgRqZGkViSuLCmPoxC8WOxYxJ3LP3S7+HXU=,iv:8JjRxlSCvmgnfmNuiJtP86I/8EzoD8bvwmSli8/4P78=,tag:fQG+NilPtZefAlpqDerE1Q==,type:str]
neuvector_id: ENC[AES256_GCM,data:V+r/L0sY5x5I,iv:Lr1BYqTE0oImK6lTB+QeCV+c3Hq791YCPfIMZzuYyho=,tag:1IcwVpJa65nN8Oaauc8hCA==,type:str]
neuvector_addr: ENC[AES256_GCM,data:y3CjL8uLetnymAmV8zjp1RI=,iv:ipjcgVlr9GICpIQgINW29Cg/VR1bDTGQicuqPtaouo8=,tag:SHxPvoGKOXeKkRQcjVtqaw==,type:str]
neuvector_client_secret: ENC[AES256_GCM,data:Cr4w3888GOYhEjB3WnYwDrWJQ2/cym+dypsKB673m8I=,iv:ZobhMcsPQPahqpeShRQfde++JDUdCO4aMEHe4mxOZjU=,tag:zTNmDOUh8jp2XH5wTVgRBg==,type:str]
gitea_id: ENC[AES256_GCM,data:6z2AnU0=,iv:Hguol+Fts773nDOkB/04vrHBbddAy78CTs3gxH4SXO4=,tag:+/fjgzKGEhNs+NjSqvoaBA==,type:str]
gitea_addr: ENC[AES256_GCM,data:iSOXQKE7R4OlhTU/OS5M2Hzw,iv:UBhi88AxOTPafc+OGYfePN/DoeP0Ny/Q4d5xNSr6rTY=,tag:Re0fVN4vHFbh5ZxJS3Bx0A==,type:str]
gitea_client_secret: ENC[AES256_GCM,data:efJ+3t6u0JeXO9MHpc1ocv3R+5xli/CouTfCoB+qX2w=,iv:2ij4exScDJPns9WTOwmZXUR7UOM9zCjmtbhJUpwjkeo=,tag:jXU1SQaGE5d5L6qZ764tcA==,type:str]
rancher_id: ENC[AES256_GCM,data:xkhRVG5Zgg==,iv:pF8t7U1c00Dyj/MXWaNUgJ2qv/vHRoeyfuZgIVq/QRg=,tag:APusbqyr9F+/w7F4xzP3Cg==,type:str]
rancher_addr: ENC[AES256_GCM,data:B2Y8VOnAHvr7mLmuE0N2,iv:9JhAYCOAzwmQG7gXDf7Js/tUOFfBwxFWy5wHyC1xVNc=,tag:Tncg45FrcF1urFxV70BMZA==,type:str]
rancher_client_secret: ENC[AES256_GCM,data:VgdB7kOkU37Rk2BxsFaViXBQThqY+iZT4FBGGZ2Kmr0=,iv:ontKXQvywU+SPMcsScqpbL0V9BIah8frXkmKdvthCOY=,tag:T2Lhy6Afl6FwF2+FR24RtA==,type:str]
terraform_client: ENC[AES256_GCM,data:jAYtouosyBrGvJAxwO/ybECU9A==,iv:Iq5D6AHQ6musHwNM81/haosqb/spWXPJ98LZmvPvwaQ=,tag:WQdguIZ8AisBmZqoeern8g==,type:str]
terraform_client_secret: ENC[AES256_GCM,data:hQz2sw+HxzVepYPTUsJkb47hDWegL0RUIxaCVdNLb1kBvxuTBhz7,iv:3T7hm0KW7DLVckMRWU2G30FNeTdVLA6m0QKCclbgZow=,tag:b8EZgTOiORodaARwAkP4xA==,type:str]
terraform_client_role: ENC[AES256_GCM,data:qSAqBMg=,iv:LI/NgEYcjDtxrItOxMuWXxyY1lM0DcloWdE6cr9J4Ak=,tag:AYPXxhUtWHVMCRTuYJdOXQ==,type:str]
gitea2_id: ENC[AES256_GCM,data:dqEQAcq/,iv:UwhjaUeQ/uawqQZCQwVYIKkbeTfMaIBz2a6wr14Mgr4=,tag:bv3UxTPcl3Y3OCiBX7zaEA==,type:str]
gitea2_addr: ENC[AES256_GCM,data:yxGb+ZrY9m2fvrjPl6qu+lQ+,iv:aVC34DJDUYGti4wtKvZtlJlPlTefcmCmeudgKHyCCMU=,tag:KGh3ugoOkHS3auv0Gi0o0Q==,type:str]
gitea2_client_secret: ENC[AES256_GCM,data:WxFzfN/bBjYJTRpRqxwaW8NyBB3RB3/qUKZOwcYvTGo=,iv:Bd9rtGZMkaMi2beYwj6o5LDy/NEa28FVL8gmUe7aMck=,tag:KfxoQLqs+L8rTY3aTG8CiA==,type:str]
sops:
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-06-07T02:39:19Z"
          enc: vault:v1:D+5Gg5fvuvr8Xs0rT5rioIItgIDEQdS3+u95sLxKszFowsAYAZ01QxMygyLGeLdipMPlTSZWwAHtSbK2
    age:
        - recipient: age17nu5r47gk7y79vtg7zmnrxxedxltm25t8wxry3g73w7t844mqs8qgh96es
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN2g3Y2pXQ1Rid3REL01K
            d1RmSnE1bHBQRlZHQ2hmRk9IcTBiUUR2TTB3ClM1clJxdElMOG1MU3Q5eG5tbTBW
            bG1rV0xZOWZEckF6cTlYOXhOVC9XNlEKLS0tIGkvdXFCb3EwUGpNek8yQjlBd0do
            ckVZSUQzTU0velZZVnloVTdSUGhCRk0KWvB2sMhHrUHF4VtLMGtpQp2X6t1CnivW
            +LN1UuQYLwRjgZ7VCKAsDoDiBP7imB0wGB43675oplOZIJ/rwmyOig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-04T02:11:23Z"
    mac: ENC[AES256_GCM,data:h11k1HUQx9mtXjK5icLvYwM2Wit0mFkeJ/XuJO7j/2fWWWAFJCrZgFMbYm2n0bR3peDAfIwlgBiaVlcxsu+iWXsy4OdS/NoBNJ0MZkHBFurmgY6Zi9jcBL7dNNplP8Jt27emUwZaXlkt/ed6+fI7VAHBSBLyEBMMBTB0ladVcqM=,iv:ySpfDXB4UMc8cOm1wFgzgtnOSazAkPH0yUuKfW/SDQ0=,tag:YBYEjwkyWd80mo6fSqkVeg==,type:str]
    pgp:
        - created_at: "2023-06-07T02:39:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA9Qs/eFVrZ++AQ/1Fui9MTDhxSp+qsYMc4Ijvr/b7ChkKzodxB0zQqB0+PrG
            qRLlWd1PAEI/EED89QjOsriUAcsZFqwDUphiteK7duSFuUCTyhHBvz6BrQgeHYhd
            DIPhHBouYTwbuiy5SlakkvBqgVz4wfu9DR4snF4oGg1hEiekKvjKRAXl5HqXrTjC
            M/tQ0iIgLDFzApBpSiE/t4f45133KmPJpc34c0W7CO8aVO/+By11sc+h93wleWJi
            zmbiwwifv/tlvMh8uBz7yXubyz/NhQrQ1YdpHuiW8o16Lqg4P6zr8Z5UcXZuv5DG
            dYxd6ALyNEsOYYMilikcWmVc2fH9tUWClkmO84MslLpTNOIbezlVr7v24BBg99N9
            xIkwd91odSyQ+/ufsKGryAZnyRZ+KAbL9epfAQsR5vMfRwNEEVyI14QTG8K5MvqR
            rNXQhyP4ts54CipmcjVYd8Vehif5zeFICLKiby0YoEHUJgFSgUf8IWlOaX9mgKam
            E10QRigxjSASmgaV31EqxVyFux0l1+cUuYFeo6xce3SHN6IHgUfKgJ6Lc+OLMbgZ
            yvzx6CgJlShDzyvCCLN/5tbbpBVvIVC0mO7yHxNZb1BUbr5+WBjuW3JRdtRvZWNJ
            yS4BYBCc8hSE7EEFQg2AJS2w2uMX0wHW45tFR0mTv7yNa+XLCeXBYA/rHBBpCdJe
            ATfjVb0625f7JeO0HQk38V8Gt1rreb6wRWjO9VmbSCry038TaEh5ndipUPpQ7uIT
            FEwWWGniz8OrYP0p69KoMemnb3tAzClMGV8Dy2ZalEZdXZ+ndze0YVA0T0ohhA==
            =Pg+w
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    unencrypted_suffix: _unencrypted
    version: 3.10.2
