keycloak_user: ENC[AES256_GCM,data:y2Hf/BemBw==,iv:RJ4VDUP1K+8+mMPIT3Tum+coidSxiWjMdJ+yfMbiV2E=,tag:XlYsNT4lBNWk0zRTSuo5PQ==,type:str]
keycloak_password: ENC[AES256_GCM,data:i38Ctz3ITfSbjVGgvkXsZ1LBTQFhQF0olUl2FaG2,iv:jqecbfZ5fcGEno63lp6kk1pg4vnJXXW27xDeqNPpgkk=,tag:ct6E3OzpRv02+zIV1oIgjQ==,type:str]
keycloak_realm: ENC[AES256_GCM,data:81VW1jp5,iv:0400Wi5vlOfhxUjYIxZhmMdJLYeRjAZ6WkcxCwVfNnE=,tag:63+PxDFfm9Xfp9uMpEVUPw==,type:str]
keycloak_addr: ENC[AES256_GCM,data:u+KGgFfWDTdsepa3L/yscw==,iv:NFzXCJUOVSkckBam4qRie7EhW7BMLLzPJMmpPjLujGI=,tag:69i5ruokMGBGJjpeb3cHOA==,type:str]
bind_credential: ENC[AES256_GCM,data:z2MLeI+4UBDwy4vXuvHGj/QlsD3NEeql,iv:MYInj8uiXzTIkEoUEQR2UroTKpIvewqR6ZmdMI1YOEw=,tag:xdZtVC4OSRko9otVbvQj4w==,type:str]
harbor_id: ENC[AES256_GCM,data:Cr8Ds97je8WsCg==,iv:mYIXhDRuLuoDlc4jZWZ/z7A1ujYm/6KlDcCF61QsoSs=,tag:PLcU4Kg0Ioh4zmb40pqoag==,type:str]
harbor_addr: ENC[AES256_GCM,data:tibogMrKs/0HferjTORjFqa9zml9IA==,iv:92p79egtkyQOZJuGkdwn8vd7eUMA/EvVvl6swBCZupI=,tag:zGLfQW9XffewZGaNuQUYbw==,type:str]
harbor_client_secret: ENC[AES256_GCM,data:LOe930oCzgRqZGkViSuLCmPoxC8WOxYxJ3LP3S7+HXU=,iv:8JjRxlSCvmgnfmNuiJtP86I/8EzoD8bvwmSli8/4P78=,tag:fQG+NilPtZefAlpqDerE1Q==,type:str]
neuvector_id: ENC[AES256_GCM,data:V+r/L0sY5x5I,iv:Lr1BYqTE0oImK6lTB+QeCV+c3Hq791YCPfIMZzuYyho=,tag:1IcwVpJa65nN8Oaauc8hCA==,type:str]
neuvector_addr: ENC[AES256_GCM,data:y3CjL8uLetnymAmV8zjp1RI=,iv:ipjcgVlr9GICpIQgINW29Cg/VR1bDTGQicuqPtaouo8=,tag:SHxPvoGKOXeKkRQcjVtqaw==,type:str]
neuvector_client_secret: ENC[AES256_GCM,data:Cr4w3888GOYhEjB3WnYwDrWJQ2/cym+dypsKB673m8I=,iv:ZobhMcsPQPahqpeShRQfde++JDUdCO4aMEHe4mxOZjU=,tag:zTNmDOUh8jp2XH5wTVgRBg==,type:str]
gitea_id: ENC[AES256_GCM,data:6z2AnU0=,iv:Hguol+Fts773nDOkB/04vrHBbddAy78CTs3gxH4SXO4=,tag:+/fjgzKGEhNs+NjSqvoaBA==,type:str]
gitea_addr: ENC[AES256_GCM,data:iSOXQKE7R4OlhTU/OS5M2Hzw,iv:UBhi88AxOTPafc+OGYfePN/DoeP0Ny/Q4d5xNSr6rTY=,tag:Re0fVN4vHFbh5ZxJS3Bx0A==,type:str]
gitea_client_secret: ENC[AES256_GCM,data:efJ+3t6u0JeXO9MHpc1ocv3R+5xli/CouTfCoB+qX2w=,iv:2ij4exScDJPns9WTOwmZXUR7UOM9zCjmtbhJUpwjkeo=,tag:jXU1SQaGE5d5L6qZ764tcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://hashivault.rmcd.win
          engine_path: sops
          key_name: sops-user
          created_at: "2023-06-07T02:39:19Z"
          enc: vault:v1:D+5Gg5fvuvr8Xs0rT5rioIItgIDEQdS3+u95sLxKszFowsAYAZ01QxMygyLGeLdipMPlTSZWwAHtSbK2
    age:
        - recipient: age17nu5r47gk7y79vtg7zmnrxxedxltm25t8wxry3g73w7t844mqs8qgh96es
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN2g3Y2pXQ1Rid3REL01K
            d1RmSnE1bHBQRlZHQ2hmRk9IcTBiUUR2TTB3ClM1clJxdElMOG1MU3Q5eG5tbTBW
            bG1rV0xZOWZEckF6cTlYOXhOVC9XNlEKLS0tIGkvdXFCb3EwUGpNek8yQjlBd0do
            ckVZSUQzTU0velZZVnloVTdSUGhCRk0KWvB2sMhHrUHF4VtLMGtpQp2X6t1CnivW
            +LN1UuQYLwRjgZ7VCKAsDoDiBP7imB0wGB43675oplOZIJ/rwmyOig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-16T03:02:09Z"
    mac: ENC[AES256_GCM,data:cTz+8Fa8hWXmbJH1lLjydQr7BgYLyeH7gqTha13ta8G10mgaaAub1SbLNrrU3zTgabr+vsPhzsxjOj3GKix4cmvDLWCZYJ9pqLEeDhwQhjY4eMevPSVHvABJxAeG7ipUawnWv2KaamnqNsyxIkSKg0wTn6ME0pDnIwbbdcJ5HLM=,iv:udC4gx7WppQ7+n97aB8Sh8NmPWN3EmVXsiKzUHFeEK8=,tag:MHlPtQLX8w8jG2gA3DkyYw==,type:str]
    pgp:
        - created_at: "2023-06-07T02:39:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA9Qs/eFVrZ++AQ/1Fui9MTDhxSp+qsYMc4Ijvr/b7ChkKzodxB0zQqB0+PrG
            qRLlWd1PAEI/EED89QjOsriUAcsZFqwDUphiteK7duSFuUCTyhHBvz6BrQgeHYhd
            DIPhHBouYTwbuiy5SlakkvBqgVz4wfu9DR4snF4oGg1hEiekKvjKRAXl5HqXrTjC
            M/tQ0iIgLDFzApBpSiE/t4f45133KmPJpc34c0W7CO8aVO/+By11sc+h93wleWJi
            zmbiwwifv/tlvMh8uBz7yXubyz/NhQrQ1YdpHuiW8o16Lqg4P6zr8Z5UcXZuv5DG
            dYxd6ALyNEsOYYMilikcWmVc2fH9tUWClkmO84MslLpTNOIbezlVr7v24BBg99N9
            xIkwd91odSyQ+/ufsKGryAZnyRZ+KAbL9epfAQsR5vMfRwNEEVyI14QTG8K5MvqR
            rNXQhyP4ts54CipmcjVYd8Vehif5zeFICLKiby0YoEHUJgFSgUf8IWlOaX9mgKam
            E10QRigxjSASmgaV31EqxVyFux0l1+cUuYFeo6xce3SHN6IHgUfKgJ6Lc+OLMbgZ
            yvzx6CgJlShDzyvCCLN/5tbbpBVvIVC0mO7yHxNZb1BUbr5+WBjuW3JRdtRvZWNJ
            yS4BYBCc8hSE7EEFQg2AJS2w2uMX0wHW45tFR0mTv7yNa+XLCeXBYA/rHBBpCdJe
            ATfjVb0625f7JeO0HQk38V8Gt1rreb6wRWjO9VmbSCry038TaEh5ndipUPpQ7uIT
            FEwWWGniz8OrYP0p69KoMemnb3tAzClMGV8Dy2ZalEZdXZ+ndze0YVA0T0ohhA==
            =Pg+w
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    unencrypted_suffix: _unencrypted
    version: 3.7.3
