# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:+8mmtre3IC/Q2Lwe8WijvVKf3J6TFj/jPlozVkw9cg5yNEh21gk7cA==,iv:K8qqjv8hX+2v/nFsZjFBIuOZkQOviLLfskZylNQ5mcQ=,tag:B8PTqHHid2DeNEnluXawnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-17T03:08:31Z"
    mac: ENC[AES256_GCM,data:8IaNJkV5NJCee9Pqq/nCBQ5vZKp1+lsCAQ+ADdNtVwW5kKdaNTs0t41E9XKsHSxBGcC7cEyagOtjejnj5BPcm6oOXPT+zBaGdlLkFNeXejGsnwIR+nVUnTFodtE60erX3PCoIR7TghUgjDU7yMSAVWWquyWVnFkz3bIdECPHe8A=,iv:+XhtFKeJFDCfcbv1xAc64j9BZdgM4cl2tf+5vmmTjyc=,tag:9z9dWAD7yGdia/MjPoBPjA==,type:str]
    pgp:
        - created_at: "2023-05-17T03:08:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxnLN2eNn/kQAQ//frKqLqdCEqwIl/NSMg8861X8it9o/u1ghZFpwtYf59Rf
            Tx6VrEfgi2j65hG0QjAFWbaxNCVipGvubqyyDhRjt1hLpqFtvSLzOHLis1LijY6G
            VKeYCuVcu/o8sCbDi2V5e0KxczitlZ03ThQmVR1vbGBfVxM6iQeVol4HJ0EDHTQk
            A+H9xB5/CaU1v/nUFMizd3xNR/WN0jXOGEQwGjkCn0/iWZIrGMh22QngObyAzWWB
            LpSqIMF4TniWCXbPVHB5uaQaoJS5HiBuArPFLxSNUlDtzAgYlGMJiMjuNEujPGxu
            Itnh2g14ASGQ2tS37vPkH+2YF6I9Y82f5l3noEpoEqn4tQfHa9XJcfNBtjXdRkEg
            HWT63LACbXZNQfPb3Rxf2vkLviJUDKOFhnQ/hZW5fM+2mpTpDtXOXTMy5wg/5Gih
            d1Pwh+Go9zWAuxNw2WuWVKm/jauSYzsIzKCAtdsp7Zc4r6NYVL1qSa1OPzy+L5id
            QVIuTPjXYvcxSpiQf36vo0Um9MqW6p0iqWGouAXVhQRTVvclDYqbky0vp+5vxuaJ
            cIdpdqp2E/fejWOnLejVUl6YTylYezB+WkHIoj7DjtmYT3yxLcJd+8X9hYTxE+x5
            ONkPqRbCZbRXX1+a0WtsJP7MoiCgSDkRoyuIzxFGQ8r/ISMnNHUMhhSVaFI1gk3U
            aAEJAhBtV8svf+29ap2TZaMgusocpmQffu7VmY2r7EVks3Tn41gPF1L4mAB2THLT
            t9/Cl9y2PPsh0UE2/QCoIbAs9JDYIncmqzPL1bHlY/+0qyusOpTfe7q9cs0Lwivf
            saJld7sRMZoJ
            =qNlt
            -----END PGP MESSAGE-----
          fp: E6D978BF2C0B69227A85D9BA04812C60A830A726
        - created_at: "2023-05-17T03:08:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59Pualoj6WCAQ//dv80b2Rr+Y/b/PQLrnfocOSf6BTZ/XP6xnVcje5k5kKl
            zHdIzQynA6CoFFy50cuYLtSGD1b133d7E5PLh6nG35TTDJJw2wSSfPt42zM/F0qQ
            dBhJCGgoag/OGG+ckdLXO9WVkglU7Q+8HAcYUALEZTLjYzmPXRYEC2lxgMIJ48zL
            MKRN34RtgfAv9rZCppo9NmzEHE/pLUHngELt9z/NE0Y8AkTIuZJSLqdW5xIrgnLv
            DomKIaNSY6P7shnkTKiSPf7hsspdEq1uj5AjHo80cKIjrVESFTDD3GeXTiFHFmRm
            7fW+N1Ke4rtH4WCBKb+Uvujn5hcJNGj/3ECIkSa6lIg7dj2DNSsBjFTUk1UWfZG5
            QCWNQdJu5eutk9+6UNAwUiEZL3QQBw6XwLWVyNFB2HKQUTgb1bHtT9/nJgOWGSJn
            BDnIYsLgBPeiAY9d+GtzN4PKRPduuNT6ClvC38xXCTRUMT2ozHJl4tkYmL36ezB0
            2K2IkoavKBJH0JbeElvOjKtppMfgvZ29CYjc21yhby5ZciJh0y2OfurdRRFph8qj
            8Z+nMgj3O8T1s+djtFWFipfK0cDmUDhidF3Zh+fZAb8vTJKiWiBhXTQjlbnIUTQc
            tTkL4zLUYYIx59bpSqhvYa3IYDScqxMOKWFylW6iaGLCU5epdaWcSrveNpWO/kLS
            XgGoSeMegC8b599pMEhVMEMwZkUraspxBG6V3mnAc8vtOhu/HVjMotZjb8xmZIYB
            gtOA7KGa+Vx9spyK9hxqBMiYIvHTR49SlU2HCOOJRaAtp7nmhUPInWcOCghMdfI=
            =bQxg
            -----END PGP MESSAGE-----
          fp: B98EF6FF6F3748661F449D0CA912302389FEB397
        - created_at: "2023-05-17T03:08:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9Qs/eFVrZ++AQ//bTOi0ghTfi9NL42a/q0G4Ys0h+bmFR2DSVjzJou3CCV9
            uSvznA3Dy1LJiGaF4qp346aFyzQOSGEtGpqAyc0LxQRSdeYUzilYzhHzUpJ6VD2c
            eXTjSzqcUNgc5K8UH0x5Kmhwhdh0qfUvBEoadOh0rBvy5cLioXleEYdk6RGeV1xO
            g03mif1SOcj2pYixIGK97ZM4h29ysmF0rZbjf8lOwgunXJy9Z1eDsBCbHfFkrwPA
            QXUec9D8bimBKe13Hr3Vr1W4/194U+Uw5zk4pIvABGdyXRCQ0KQ2EVTqdx2vKO2M
            5aaLG0Q8yzNJbJw8o8AueIUDc8vllI/QpcUjl/eIVN3BMQOhBax2bgnhjOt7+oCI
            PE6XvmV/wshubMkYXeICP/cE/uf28DgF1SiGBoj04jd2OCFLvfPiKCxL/YMWMzFV
            QdryBL1wovM/HsWV8gHmZMQMg0+3TLYBXg3cnzJSwd8VZYQBanh3dUDEnOsfATUc
            6UpIWfDCWU8MWIkoT+zfPfU378O9dQHqymBBBhdi3jv0ORW0+EjGso3itNFW7BXI
            uR/V3g7nHXgqFV0UOfZwuIS0LJPNyHkOIIMlMo57BC0SbmdzvqqVL1fyQH6YHVC7
            Ug5Z9D0k1jy37nUO/223sstTdkXeNeDS+lBHuMiLVZ33hSV1QosUUZ91XrMFi+DS
            XgGNl4JXRkJrntXnIfybXRXuEZKTKvNIGu5mrc3HmI75JRzj/1Xg17A5YnXzS3mb
            CcTRLPF8nneJIEuAU1nHAS60/ZDout8g3SEDclkp0EjPOzLC3yDAIn57WqFwjn4=
            =pwYe
            -----END PGP MESSAGE-----
          fp: 95106BD4F26A01996BDA831E6D9E63E5FF3AE8E0
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
