apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cluster.local/local-path-provisioner
parameters:
  nodePath: /var/lib/rancher/k3s/storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete