apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-local-path
provisioner: cluster.local/local-path-provisioner
parameters:
  nodePath: /opt/local-path-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete