apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
provisioner: cluster.local/local-path-provisioner
parameters:
  nodePath: /var/lib/rancher/k3s/storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete