---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: glauth
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/apps/sso/glauth/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster