---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/istio/istio-ingress/istio-gateway/app"
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: istiod
      namespace: flux-system